// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "jpeg2.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic jpeg2::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic jpeg2::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> jpeg2::ap_ST_fsm_state1 = "1";
const sc_lv<4> jpeg2::ap_ST_fsm_state2 = "10";
const sc_lv<4> jpeg2::ap_ST_fsm_state3 = "100";
const sc_lv<4> jpeg2::ap_ST_fsm_state4 = "1000";
const sc_lv<32> jpeg2::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> jpeg2::ap_const_lv32_2 = "10";
const sc_lv<32> jpeg2::ap_const_lv32_3 = "11";
const int jpeg2::C_S_AXI_DATA_WIDTH = "100000";
const sc_lv<32> jpeg2::ap_const_lv32_1 = "1";
const sc_lv<1> jpeg2::ap_const_lv1_0 = "0";
const sc_lv<1> jpeg2::ap_const_lv1_1 = "1";
const sc_lv<8> jpeg2::ap_const_lv8_FF = "11111111";
const sc_lv<8> jpeg2::ap_const_lv8_D9 = "11011001";
const bool jpeg2::ap_const_boolean_1 = true;

jpeg2::jpeg2(sc_module_name name) : sc_module(name), mVcdFile(0) {
    jpeg2_AXILiteS_s_axi_U = new jpeg2_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>("jpeg2_AXILiteS_s_axi_U");
    jpeg2_AXILiteS_s_axi_U->AWVALID(s_axi_AXILiteS_AWVALID);
    jpeg2_AXILiteS_s_axi_U->AWREADY(s_axi_AXILiteS_AWREADY);
    jpeg2_AXILiteS_s_axi_U->AWADDR(s_axi_AXILiteS_AWADDR);
    jpeg2_AXILiteS_s_axi_U->WVALID(s_axi_AXILiteS_WVALID);
    jpeg2_AXILiteS_s_axi_U->WREADY(s_axi_AXILiteS_WREADY);
    jpeg2_AXILiteS_s_axi_U->WDATA(s_axi_AXILiteS_WDATA);
    jpeg2_AXILiteS_s_axi_U->WSTRB(s_axi_AXILiteS_WSTRB);
    jpeg2_AXILiteS_s_axi_U->ARVALID(s_axi_AXILiteS_ARVALID);
    jpeg2_AXILiteS_s_axi_U->ARREADY(s_axi_AXILiteS_ARREADY);
    jpeg2_AXILiteS_s_axi_U->ARADDR(s_axi_AXILiteS_ARADDR);
    jpeg2_AXILiteS_s_axi_U->RVALID(s_axi_AXILiteS_RVALID);
    jpeg2_AXILiteS_s_axi_U->RREADY(s_axi_AXILiteS_RREADY);
    jpeg2_AXILiteS_s_axi_U->RDATA(s_axi_AXILiteS_RDATA);
    jpeg2_AXILiteS_s_axi_U->RRESP(s_axi_AXILiteS_RRESP);
    jpeg2_AXILiteS_s_axi_U->BVALID(s_axi_AXILiteS_BVALID);
    jpeg2_AXILiteS_s_axi_U->BREADY(s_axi_AXILiteS_BREADY);
    jpeg2_AXILiteS_s_axi_U->BRESP(s_axi_AXILiteS_BRESP);
    jpeg2_AXILiteS_s_axi_U->ACLK(ap_clk);
    jpeg2_AXILiteS_s_axi_U->ARESET(ap_rst_n_inv);
    jpeg2_AXILiteS_s_axi_U->ACLK_EN(ap_var_for_const0);
    jpeg2_AXILiteS_s_axi_U->ap_start(ap_start);
    jpeg2_AXILiteS_s_axi_U->interrupt(interrupt);
    jpeg2_AXILiteS_s_axi_U->ap_ready(ap_ready);
    jpeg2_AXILiteS_s_axi_U->ap_done(ap_done);
    jpeg2_AXILiteS_s_axi_U->ap_idle(ap_idle);
    jpeg1_buffer_U = new jpeg2_jpeg1_buffer("jpeg1_buffer_U");
    jpeg1_buffer_U->clk(ap_clk);
    jpeg1_buffer_U->reset(ap_rst_n_inv);
    jpeg1_buffer_U->address0(grp_encodeToJPG_fu_116_JpegEncoder_buffer_address0);
    jpeg1_buffer_U->ce0(grp_encodeToJPG_fu_116_JpegEncoder_buffer_ce0);
    jpeg1_buffer_U->we0(grp_encodeToJPG_fu_116_JpegEncoder_buffer_we0);
    jpeg1_buffer_U->d0(grp_encodeToJPG_fu_116_JpegEncoder_buffer_d0);
    jpeg1_buffer_U->q0(jpeg1_buffer_q0);
    jpeg1_buffer_U->address1(grp_encodeToJPG_fu_116_JpegEncoder_buffer_address1);
    jpeg1_buffer_U->ce1(grp_encodeToJPG_fu_116_JpegEncoder_buffer_ce1);
    jpeg1_buffer_U->we1(grp_encodeToJPG_fu_116_JpegEncoder_buffer_we1);
    jpeg1_buffer_U->d1(grp_encodeToJPG_fu_116_JpegEncoder_buffer_d1);
    jpeg1_buffer_U->q1(jpeg1_buffer_q1);
    jpeg1_m_YTable_U = new jpeg2_jpeg1_m_YTabbk("jpeg1_m_YTable_U");
    jpeg1_m_YTable_U->clk(ap_clk);
    jpeg1_m_YTable_U->reset(ap_rst_n_inv);
    jpeg1_m_YTable_U->address0(grp_encodeToJPG_fu_116_JpegEncoder_m_YTable_address0);
    jpeg1_m_YTable_U->ce0(grp_encodeToJPG_fu_116_JpegEncoder_m_YTable_ce0);
    jpeg1_m_YTable_U->we0(grp_encodeToJPG_fu_116_JpegEncoder_m_YTable_we0);
    jpeg1_m_YTable_U->d0(grp_encodeToJPG_fu_116_JpegEncoder_m_YTable_d0);
    jpeg1_m_YTable_U->q0(jpeg1_m_YTable_q0);
    jpeg1_m_CbCrTable_U = new jpeg2_jpeg1_m_YTabbk("jpeg1_m_CbCrTable_U");
    jpeg1_m_CbCrTable_U->clk(ap_clk);
    jpeg1_m_CbCrTable_U->reset(ap_rst_n_inv);
    jpeg1_m_CbCrTable_U->address0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCrTable_address0);
    jpeg1_m_CbCrTable_U->ce0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCrTable_ce0);
    jpeg1_m_CbCrTable_U->we0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCrTable_we0);
    jpeg1_m_CbCrTable_U->d0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCrTable_d0);
    jpeg1_m_CbCrTable_U->q0(jpeg1_m_CbCrTable_q0);
    jpeg1_m_Y_DC_Huffman_U = new jpeg2_jpeg1_m_Y_Dbdk("jpeg1_m_Y_DC_Huffman_U");
    jpeg1_m_Y_DC_Huffman_U->clk(ap_clk);
    jpeg1_m_Y_DC_Huffman_U->reset(ap_rst_n_inv);
    jpeg1_m_Y_DC_Huffman_U->address0(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_DC_Huffman_Table_length_address0);
    jpeg1_m_Y_DC_Huffman_U->ce0(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_DC_Huffman_Table_length_ce0);
    jpeg1_m_Y_DC_Huffman_U->we0(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_DC_Huffman_Table_length_we0);
    jpeg1_m_Y_DC_Huffman_U->d0(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_DC_Huffman_Table_length_d0);
    jpeg1_m_Y_DC_Huffman_U->q0(jpeg1_m_Y_DC_Huffman_q0);
    jpeg1_m_Y_DC_Huffman_1_U = new jpeg2_jpeg1_m_Y_Dbek("jpeg1_m_Y_DC_Huffman_1_U");
    jpeg1_m_Y_DC_Huffman_1_U->clk(ap_clk);
    jpeg1_m_Y_DC_Huffman_1_U->reset(ap_rst_n_inv);
    jpeg1_m_Y_DC_Huffman_1_U->address0(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_DC_Huffman_Table_value_address0);
    jpeg1_m_Y_DC_Huffman_1_U->ce0(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_DC_Huffman_Table_value_ce0);
    jpeg1_m_Y_DC_Huffman_1_U->we0(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_DC_Huffman_Table_value_we0);
    jpeg1_m_Y_DC_Huffman_1_U->d0(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_DC_Huffman_Table_value_d0);
    jpeg1_m_Y_DC_Huffman_1_U->q0(jpeg1_m_Y_DC_Huffman_1_q0);
    jpeg1_m_Y_AC_Huffman_U = new jpeg2_jpeg1_m_Y_Abfk("jpeg1_m_Y_AC_Huffman_U");
    jpeg1_m_Y_AC_Huffman_U->clk(ap_clk);
    jpeg1_m_Y_AC_Huffman_U->reset(ap_rst_n_inv);
    jpeg1_m_Y_AC_Huffman_U->address0(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_length_address0);
    jpeg1_m_Y_AC_Huffman_U->ce0(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_length_ce0);
    jpeg1_m_Y_AC_Huffman_U->we0(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_length_we0);
    jpeg1_m_Y_AC_Huffman_U->d0(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_length_d0);
    jpeg1_m_Y_AC_Huffman_U->q0(jpeg1_m_Y_AC_Huffman_q0);
    jpeg1_m_Y_AC_Huffman_U->address1(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_length_address1);
    jpeg1_m_Y_AC_Huffman_U->ce1(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_length_ce1);
    jpeg1_m_Y_AC_Huffman_U->q1(jpeg1_m_Y_AC_Huffman_q1);
    jpeg1_m_Y_AC_Huffman_1_U = new jpeg2_jpeg1_m_Y_Abgk("jpeg1_m_Y_AC_Huffman_1_U");
    jpeg1_m_Y_AC_Huffman_1_U->clk(ap_clk);
    jpeg1_m_Y_AC_Huffman_1_U->reset(ap_rst_n_inv);
    jpeg1_m_Y_AC_Huffman_1_U->address0(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_value_address0);
    jpeg1_m_Y_AC_Huffman_1_U->ce0(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_value_ce0);
    jpeg1_m_Y_AC_Huffman_1_U->we0(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_value_we0);
    jpeg1_m_Y_AC_Huffman_1_U->d0(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_value_d0);
    jpeg1_m_Y_AC_Huffman_1_U->q0(jpeg1_m_Y_AC_Huffman_1_q0);
    jpeg1_m_Y_AC_Huffman_1_U->address1(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_value_address1);
    jpeg1_m_Y_AC_Huffman_1_U->ce1(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_value_ce1);
    jpeg1_m_Y_AC_Huffman_1_U->q1(jpeg1_m_Y_AC_Huffman_1_q1);
    jpeg1_m_CbCr_DC_Huff_U = new jpeg2_jpeg1_m_Y_Dbdk("jpeg1_m_CbCr_DC_Huff_U");
    jpeg1_m_CbCr_DC_Huff_U->clk(ap_clk);
    jpeg1_m_CbCr_DC_Huff_U->reset(ap_rst_n_inv);
    jpeg1_m_CbCr_DC_Huff_U->address0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_DC_Huffman_Table_length_address0);
    jpeg1_m_CbCr_DC_Huff_U->ce0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_DC_Huffman_Table_length_ce0);
    jpeg1_m_CbCr_DC_Huff_U->we0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_DC_Huffman_Table_length_we0);
    jpeg1_m_CbCr_DC_Huff_U->d0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_DC_Huffman_Table_length_d0);
    jpeg1_m_CbCr_DC_Huff_U->q0(jpeg1_m_CbCr_DC_Huff_q0);
    jpeg1_m_CbCr_DC_Huff_1_U = new jpeg2_jpeg1_m_Y_Dbek("jpeg1_m_CbCr_DC_Huff_1_U");
    jpeg1_m_CbCr_DC_Huff_1_U->clk(ap_clk);
    jpeg1_m_CbCr_DC_Huff_1_U->reset(ap_rst_n_inv);
    jpeg1_m_CbCr_DC_Huff_1_U->address0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_DC_Huffman_Table_value_address0);
    jpeg1_m_CbCr_DC_Huff_1_U->ce0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_DC_Huffman_Table_value_ce0);
    jpeg1_m_CbCr_DC_Huff_1_U->we0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_DC_Huffman_Table_value_we0);
    jpeg1_m_CbCr_DC_Huff_1_U->d0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_DC_Huffman_Table_value_d0);
    jpeg1_m_CbCr_DC_Huff_1_U->q0(jpeg1_m_CbCr_DC_Huff_1_q0);
    jpeg1_m_CbCr_AC_Huff_U = new jpeg2_jpeg1_m_Y_Abfk("jpeg1_m_CbCr_AC_Huff_U");
    jpeg1_m_CbCr_AC_Huff_U->clk(ap_clk);
    jpeg1_m_CbCr_AC_Huff_U->reset(ap_rst_n_inv);
    jpeg1_m_CbCr_AC_Huff_U->address0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_length_address0);
    jpeg1_m_CbCr_AC_Huff_U->ce0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_length_ce0);
    jpeg1_m_CbCr_AC_Huff_U->we0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_length_we0);
    jpeg1_m_CbCr_AC_Huff_U->d0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_length_d0);
    jpeg1_m_CbCr_AC_Huff_U->q0(jpeg1_m_CbCr_AC_Huff_q0);
    jpeg1_m_CbCr_AC_Huff_U->address1(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_length_address1);
    jpeg1_m_CbCr_AC_Huff_U->ce1(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_length_ce1);
    jpeg1_m_CbCr_AC_Huff_U->q1(jpeg1_m_CbCr_AC_Huff_q1);
    jpeg1_m_CbCr_AC_Huff_1_U = new jpeg2_jpeg1_m_Y_Abgk("jpeg1_m_CbCr_AC_Huff_1_U");
    jpeg1_m_CbCr_AC_Huff_1_U->clk(ap_clk);
    jpeg1_m_CbCr_AC_Huff_1_U->reset(ap_rst_n_inv);
    jpeg1_m_CbCr_AC_Huff_1_U->address0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_value_address0);
    jpeg1_m_CbCr_AC_Huff_1_U->ce0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_value_ce0);
    jpeg1_m_CbCr_AC_Huff_1_U->we0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_value_we0);
    jpeg1_m_CbCr_AC_Huff_1_U->d0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_value_d0);
    jpeg1_m_CbCr_AC_Huff_1_U->q0(jpeg1_m_CbCr_AC_Huff_1_q0);
    jpeg1_m_CbCr_AC_Huff_1_U->address1(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_value_address1);
    jpeg1_m_CbCr_AC_Huff_1_U->ce1(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_value_ce1);
    jpeg1_m_CbCr_AC_Huff_1_U->q1(jpeg1_m_CbCr_AC_Huff_1_q1);
    grp_encodeToJPG_fu_116 = new encodeToJPG("grp_encodeToJPG_fu_116");
    grp_encodeToJPG_fu_116->ap_clk(ap_clk);
    grp_encodeToJPG_fu_116->ap_rst(ap_rst_n_inv);
    grp_encodeToJPG_fu_116->ap_start(grp_encodeToJPG_fu_116_ap_start);
    grp_encodeToJPG_fu_116->ap_done(grp_encodeToJPG_fu_116_ap_done);
    grp_encodeToJPG_fu_116->ap_idle(grp_encodeToJPG_fu_116_ap_idle);
    grp_encodeToJPG_fu_116->ap_ready(grp_encodeToJPG_fu_116_ap_ready);
    grp_encodeToJPG_fu_116->JpegEncoder_buffer_address0(grp_encodeToJPG_fu_116_JpegEncoder_buffer_address0);
    grp_encodeToJPG_fu_116->JpegEncoder_buffer_ce0(grp_encodeToJPG_fu_116_JpegEncoder_buffer_ce0);
    grp_encodeToJPG_fu_116->JpegEncoder_buffer_we0(grp_encodeToJPG_fu_116_JpegEncoder_buffer_we0);
    grp_encodeToJPG_fu_116->JpegEncoder_buffer_d0(grp_encodeToJPG_fu_116_JpegEncoder_buffer_d0);
    grp_encodeToJPG_fu_116->JpegEncoder_buffer_q0(jpeg1_buffer_q0);
    grp_encodeToJPG_fu_116->JpegEncoder_buffer_address1(grp_encodeToJPG_fu_116_JpegEncoder_buffer_address1);
    grp_encodeToJPG_fu_116->JpegEncoder_buffer_ce1(grp_encodeToJPG_fu_116_JpegEncoder_buffer_ce1);
    grp_encodeToJPG_fu_116->JpegEncoder_buffer_we1(grp_encodeToJPG_fu_116_JpegEncoder_buffer_we1);
    grp_encodeToJPG_fu_116->JpegEncoder_buffer_d1(grp_encodeToJPG_fu_116_JpegEncoder_buffer_d1);
    grp_encodeToJPG_fu_116->JpegEncoder_buffer_q1(jpeg1_buffer_q1);
    grp_encodeToJPG_fu_116->JpegEncoder_m_YTable_address0(grp_encodeToJPG_fu_116_JpegEncoder_m_YTable_address0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_YTable_ce0(grp_encodeToJPG_fu_116_JpegEncoder_m_YTable_ce0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_YTable_we0(grp_encodeToJPG_fu_116_JpegEncoder_m_YTable_we0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_YTable_d0(grp_encodeToJPG_fu_116_JpegEncoder_m_YTable_d0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_YTable_q0(jpeg1_m_YTable_q0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_CbCrTable_address0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCrTable_address0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_CbCrTable_ce0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCrTable_ce0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_CbCrTable_we0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCrTable_we0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_CbCrTable_d0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCrTable_d0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_CbCrTable_q0(jpeg1_m_CbCrTable_q0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_Y_DC_Huffman_Table_length_address0(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_DC_Huffman_Table_length_address0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_Y_DC_Huffman_Table_length_ce0(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_DC_Huffman_Table_length_ce0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_Y_DC_Huffman_Table_length_we0(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_DC_Huffman_Table_length_we0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_Y_DC_Huffman_Table_length_d0(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_DC_Huffman_Table_length_d0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_Y_DC_Huffman_Table_length_q0(jpeg1_m_Y_DC_Huffman_q0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_Y_DC_Huffman_Table_value_address0(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_DC_Huffman_Table_value_address0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_Y_DC_Huffman_Table_value_ce0(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_DC_Huffman_Table_value_ce0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_Y_DC_Huffman_Table_value_we0(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_DC_Huffman_Table_value_we0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_Y_DC_Huffman_Table_value_d0(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_DC_Huffman_Table_value_d0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_Y_DC_Huffman_Table_value_q0(jpeg1_m_Y_DC_Huffman_1_q0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_Y_AC_Huffman_Table_length_address0(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_length_address0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_Y_AC_Huffman_Table_length_ce0(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_length_ce0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_Y_AC_Huffman_Table_length_we0(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_length_we0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_Y_AC_Huffman_Table_length_d0(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_length_d0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_Y_AC_Huffman_Table_length_q0(jpeg1_m_Y_AC_Huffman_q0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_Y_AC_Huffman_Table_length_address1(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_length_address1);
    grp_encodeToJPG_fu_116->JpegEncoder_m_Y_AC_Huffman_Table_length_ce1(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_length_ce1);
    grp_encodeToJPG_fu_116->JpegEncoder_m_Y_AC_Huffman_Table_length_q1(jpeg1_m_Y_AC_Huffman_q1);
    grp_encodeToJPG_fu_116->JpegEncoder_m_Y_AC_Huffman_Table_value_address0(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_value_address0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_Y_AC_Huffman_Table_value_ce0(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_value_ce0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_Y_AC_Huffman_Table_value_we0(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_value_we0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_Y_AC_Huffman_Table_value_d0(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_value_d0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_Y_AC_Huffman_Table_value_q0(jpeg1_m_Y_AC_Huffman_1_q0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_Y_AC_Huffman_Table_value_address1(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_value_address1);
    grp_encodeToJPG_fu_116->JpegEncoder_m_Y_AC_Huffman_Table_value_ce1(grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_value_ce1);
    grp_encodeToJPG_fu_116->JpegEncoder_m_Y_AC_Huffman_Table_value_q1(jpeg1_m_Y_AC_Huffman_1_q1);
    grp_encodeToJPG_fu_116->JpegEncoder_m_CbCr_DC_Huffman_Table_length_address0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_DC_Huffman_Table_length_address0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_CbCr_DC_Huffman_Table_length_ce0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_DC_Huffman_Table_length_ce0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_CbCr_DC_Huffman_Table_length_we0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_DC_Huffman_Table_length_we0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_CbCr_DC_Huffman_Table_length_d0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_DC_Huffman_Table_length_d0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_CbCr_DC_Huffman_Table_length_q0(jpeg1_m_CbCr_DC_Huff_q0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_CbCr_DC_Huffman_Table_value_address0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_DC_Huffman_Table_value_address0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_CbCr_DC_Huffman_Table_value_ce0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_DC_Huffman_Table_value_ce0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_CbCr_DC_Huffman_Table_value_we0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_DC_Huffman_Table_value_we0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_CbCr_DC_Huffman_Table_value_d0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_DC_Huffman_Table_value_d0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_CbCr_DC_Huffman_Table_value_q0(jpeg1_m_CbCr_DC_Huff_1_q0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_CbCr_AC_Huffman_Table_length_address0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_length_address0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_CbCr_AC_Huffman_Table_length_ce0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_length_ce0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_CbCr_AC_Huffman_Table_length_we0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_length_we0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_CbCr_AC_Huffman_Table_length_d0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_length_d0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_CbCr_AC_Huffman_Table_length_q0(jpeg1_m_CbCr_AC_Huff_q0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_CbCr_AC_Huffman_Table_length_address1(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_length_address1);
    grp_encodeToJPG_fu_116->JpegEncoder_m_CbCr_AC_Huffman_Table_length_ce1(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_length_ce1);
    grp_encodeToJPG_fu_116->JpegEncoder_m_CbCr_AC_Huffman_Table_length_q1(jpeg1_m_CbCr_AC_Huff_q1);
    grp_encodeToJPG_fu_116->JpegEncoder_m_CbCr_AC_Huffman_Table_value_address0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_value_address0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_CbCr_AC_Huffman_Table_value_ce0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_value_ce0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_CbCr_AC_Huffman_Table_value_we0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_value_we0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_CbCr_AC_Huffman_Table_value_d0(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_value_d0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_CbCr_AC_Huffman_Table_value_q0(jpeg1_m_CbCr_AC_Huff_1_q0);
    grp_encodeToJPG_fu_116->JpegEncoder_m_CbCr_AC_Huffman_Table_value_address1(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_value_address1);
    grp_encodeToJPG_fu_116->JpegEncoder_m_CbCr_AC_Huffman_Table_value_ce1(grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_value_ce1);
    grp_encodeToJPG_fu_116->JpegEncoder_m_CbCr_AC_Huffman_Table_value_q1(jpeg1_m_CbCr_AC_Huff_1_q1);
    grp_encodeToJPG_fu_116->rgb_in_TDATA(rgb_in_TDATA);
    grp_encodeToJPG_fu_116->rgb_in_TVALID(rgb_in_TVALID);
    grp_encodeToJPG_fu_116->rgb_in_TREADY(grp_encodeToJPG_fu_116_rgb_in_TREADY);
    grp_encodeToJPG_fu_116->rgb_in_TKEEP(rgb_in_TKEEP);
    grp_encodeToJPG_fu_116->rgb_in_TSTRB(rgb_in_TSTRB);
    grp_encodeToJPG_fu_116->rgb_in_TLAST(rgb_in_TLAST);
    grp_encodeToJPG_fu_116->jpeg_out_TDATA(grp_encodeToJPG_fu_116_jpeg_out_TDATA);
    grp_encodeToJPG_fu_116->jpeg_out_TVALID(grp_encodeToJPG_fu_116_jpeg_out_TVALID);
    grp_encodeToJPG_fu_116->jpeg_out_TREADY(grp_encodeToJPG_fu_116_jpeg_out_TREADY);
    grp_encodeToJPG_fu_116->jpeg_out_TKEEP(grp_encodeToJPG_fu_116_jpeg_out_TKEEP);
    grp_encodeToJPG_fu_116->jpeg_out_TSTRB(grp_encodeToJPG_fu_116_jpeg_out_TSTRB);
    grp_encodeToJPG_fu_116->jpeg_out_TLAST(grp_encodeToJPG_fu_116_jpeg_out_TLAST);
    grp_p_write_byte_s_fu_184 = new p_write_byte_s("grp_p_write_byte_s_fu_184");
    grp_p_write_byte_s_fu_184->ap_clk(ap_clk);
    grp_p_write_byte_s_fu_184->ap_rst(ap_rst_n_inv);
    grp_p_write_byte_s_fu_184->ap_start(grp_p_write_byte_s_fu_184_ap_start);
    grp_p_write_byte_s_fu_184->ap_done(grp_p_write_byte_s_fu_184_ap_done);
    grp_p_write_byte_s_fu_184->ap_idle(grp_p_write_byte_s_fu_184_ap_idle);
    grp_p_write_byte_s_fu_184->ap_ready(grp_p_write_byte_s_fu_184_ap_ready);
    grp_p_write_byte_s_fu_184->JpegEncoder_outhebyte_last_V_read(grp_p_write_byte_s_fu_184_JpegEncoder_outhebyte_last_V_read);
    grp_p_write_byte_s_fu_184->value_r(grp_p_write_byte_s_fu_184_value_r);
    grp_p_write_byte_s_fu_184->jpeg_out_TDATA(grp_p_write_byte_s_fu_184_jpeg_out_TDATA);
    grp_p_write_byte_s_fu_184->jpeg_out_TVALID(grp_p_write_byte_s_fu_184_jpeg_out_TVALID);
    grp_p_write_byte_s_fu_184->jpeg_out_TREADY(grp_p_write_byte_s_fu_184_jpeg_out_TREADY);
    grp_p_write_byte_s_fu_184->jpeg_out_TKEEP(grp_p_write_byte_s_fu_184_jpeg_out_TKEEP);
    grp_p_write_byte_s_fu_184->jpeg_out_TSTRB(grp_p_write_byte_s_fu_184_jpeg_out_TSTRB);
    grp_p_write_byte_s_fu_184->jpeg_out_TLAST(grp_p_write_byte_s_fu_184_jpeg_out_TLAST);
    grp_p_write_byte_s_fu_184->ap_return(grp_p_write_byte_s_fu_184_ap_return);
    grp_p_write_byte_s_fu_184->jpeg_out_TDATA_blk_n(grp_p_write_byte_s_fu_184_jpeg_out_TDATA_blk_n);
    grp_p_write_byte_s_fu_184->ap_ce(grp_p_write_byte_s_fu_184_ap_ce);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( grp_p_write_byte_s_fu_184_jpeg_out_TDATA_blk_n );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( grp_p_write_byte_s_fu_184_jpeg_out_TDATA_blk_n );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_grp_encodeToJPG_fu_116_ap_start);
    sensitive << ( grp_encodeToJPG_fu_116_ap_start_reg );

    SC_METHOD(thread_grp_encodeToJPG_fu_116_jpeg_out_TREADY);
    sensitive << ( jpeg_out_TREADY );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_grp_p_write_byte_s_fu_184_JpegEncoder_outhebyte_last_V_read);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_grp_p_write_byte_s_fu_184_ap_ce);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_grp_p_write_byte_s_fu_184_ap_start);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_grp_p_write_byte_s_fu_184_jpeg_out_TREADY);
    sensitive << ( jpeg_out_TREADY );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_grp_p_write_byte_s_fu_184_value_r);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_jpeg_out_TDATA);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( grp_encodeToJPG_fu_116_jpeg_out_TDATA );
    sensitive << ( grp_encodeToJPG_fu_116_jpeg_out_TVALID );
    sensitive << ( grp_p_write_byte_s_fu_184_jpeg_out_TDATA );
    sensitive << ( grp_p_write_byte_s_fu_184_jpeg_out_TVALID );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_jpeg_out_TDATA_blk_n);
    sensitive << ( grp_p_write_byte_s_fu_184_jpeg_out_TDATA_blk_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_jpeg_out_TKEEP);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( grp_encodeToJPG_fu_116_jpeg_out_TVALID );
    sensitive << ( grp_encodeToJPG_fu_116_jpeg_out_TKEEP );
    sensitive << ( grp_p_write_byte_s_fu_184_jpeg_out_TVALID );
    sensitive << ( grp_p_write_byte_s_fu_184_jpeg_out_TKEEP );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_jpeg_out_TLAST);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( grp_encodeToJPG_fu_116_jpeg_out_TVALID );
    sensitive << ( grp_encodeToJPG_fu_116_jpeg_out_TLAST );
    sensitive << ( grp_p_write_byte_s_fu_184_jpeg_out_TVALID );
    sensitive << ( grp_p_write_byte_s_fu_184_jpeg_out_TLAST );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_jpeg_out_TSTRB);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( grp_encodeToJPG_fu_116_jpeg_out_TVALID );
    sensitive << ( grp_encodeToJPG_fu_116_jpeg_out_TSTRB );
    sensitive << ( grp_p_write_byte_s_fu_184_jpeg_out_TVALID );
    sensitive << ( grp_p_write_byte_s_fu_184_jpeg_out_TSTRB );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_jpeg_out_TVALID);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( grp_encodeToJPG_fu_116_jpeg_out_TVALID );
    sensitive << ( grp_p_write_byte_s_fu_184_jpeg_out_TVALID );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_rgb_in_TREADY);
    sensitive << ( grp_encodeToJPG_fu_116_rgb_in_TREADY );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( grp_p_write_byte_s_fu_184_jpeg_out_TDATA_blk_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( grp_encodeToJPG_fu_116_ap_done );
    sensitive << ( ap_CS_fsm_state2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "0001";
    grp_encodeToJPG_fu_116_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "jpeg2_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, rgb_in_TDATA, "(port)rgb_in_TDATA");
    sc_trace(mVcdFile, rgb_in_TVALID, "(port)rgb_in_TVALID");
    sc_trace(mVcdFile, rgb_in_TREADY, "(port)rgb_in_TREADY");
    sc_trace(mVcdFile, rgb_in_TKEEP, "(port)rgb_in_TKEEP");
    sc_trace(mVcdFile, rgb_in_TSTRB, "(port)rgb_in_TSTRB");
    sc_trace(mVcdFile, rgb_in_TLAST, "(port)rgb_in_TLAST");
    sc_trace(mVcdFile, jpeg_out_TDATA, "(port)jpeg_out_TDATA");
    sc_trace(mVcdFile, jpeg_out_TVALID, "(port)jpeg_out_TVALID");
    sc_trace(mVcdFile, jpeg_out_TREADY, "(port)jpeg_out_TREADY");
    sc_trace(mVcdFile, jpeg_out_TKEEP, "(port)jpeg_out_TKEEP");
    sc_trace(mVcdFile, jpeg_out_TSTRB, "(port)jpeg_out_TSTRB");
    sc_trace(mVcdFile, jpeg_out_TLAST, "(port)jpeg_out_TLAST");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWVALID, "(port)s_axi_AXILiteS_AWVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWREADY, "(port)s_axi_AXILiteS_AWREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWADDR, "(port)s_axi_AXILiteS_AWADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_WVALID, "(port)s_axi_AXILiteS_WVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_WREADY, "(port)s_axi_AXILiteS_WREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_WDATA, "(port)s_axi_AXILiteS_WDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_WSTRB, "(port)s_axi_AXILiteS_WSTRB");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARVALID, "(port)s_axi_AXILiteS_ARVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARREADY, "(port)s_axi_AXILiteS_ARREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARADDR, "(port)s_axi_AXILiteS_ARADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_RVALID, "(port)s_axi_AXILiteS_RVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_RREADY, "(port)s_axi_AXILiteS_RREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_RDATA, "(port)s_axi_AXILiteS_RDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_RRESP, "(port)s_axi_AXILiteS_RRESP");
    sc_trace(mVcdFile, s_axi_AXILiteS_BVALID, "(port)s_axi_AXILiteS_BVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_BREADY, "(port)s_axi_AXILiteS_BREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_BRESP, "(port)s_axi_AXILiteS_BRESP");
    sc_trace(mVcdFile, interrupt, "(port)interrupt");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, ap_start, "ap_start");
    sc_trace(mVcdFile, ap_done, "ap_done");
    sc_trace(mVcdFile, ap_idle, "ap_idle");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_ready, "ap_ready");
    sc_trace(mVcdFile, grp_p_write_byte_s_fu_184_jpeg_out_TDATA_blk_n, "grp_p_write_byte_s_fu_184_jpeg_out_TDATA_blk_n");
    sc_trace(mVcdFile, jpeg_out_TDATA_blk_n, "jpeg_out_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, jpeg1_buffer_q0, "jpeg1_buffer_q0");
    sc_trace(mVcdFile, jpeg1_buffer_q1, "jpeg1_buffer_q1");
    sc_trace(mVcdFile, jpeg1_m_YTable_q0, "jpeg1_m_YTable_q0");
    sc_trace(mVcdFile, jpeg1_m_CbCrTable_q0, "jpeg1_m_CbCrTable_q0");
    sc_trace(mVcdFile, jpeg1_m_Y_DC_Huffman_q0, "jpeg1_m_Y_DC_Huffman_q0");
    sc_trace(mVcdFile, jpeg1_m_Y_DC_Huffman_1_q0, "jpeg1_m_Y_DC_Huffman_1_q0");
    sc_trace(mVcdFile, jpeg1_m_Y_AC_Huffman_q0, "jpeg1_m_Y_AC_Huffman_q0");
    sc_trace(mVcdFile, jpeg1_m_Y_AC_Huffman_q1, "jpeg1_m_Y_AC_Huffman_q1");
    sc_trace(mVcdFile, jpeg1_m_Y_AC_Huffman_1_q0, "jpeg1_m_Y_AC_Huffman_1_q0");
    sc_trace(mVcdFile, jpeg1_m_Y_AC_Huffman_1_q1, "jpeg1_m_Y_AC_Huffman_1_q1");
    sc_trace(mVcdFile, jpeg1_m_CbCr_DC_Huff_q0, "jpeg1_m_CbCr_DC_Huff_q0");
    sc_trace(mVcdFile, jpeg1_m_CbCr_DC_Huff_1_q0, "jpeg1_m_CbCr_DC_Huff_1_q0");
    sc_trace(mVcdFile, jpeg1_m_CbCr_AC_Huff_q0, "jpeg1_m_CbCr_AC_Huff_q0");
    sc_trace(mVcdFile, jpeg1_m_CbCr_AC_Huff_q1, "jpeg1_m_CbCr_AC_Huff_q1");
    sc_trace(mVcdFile, jpeg1_m_CbCr_AC_Huff_1_q0, "jpeg1_m_CbCr_AC_Huff_1_q0");
    sc_trace(mVcdFile, jpeg1_m_CbCr_AC_Huff_1_q1, "jpeg1_m_CbCr_AC_Huff_1_q1");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_ap_start, "grp_encodeToJPG_fu_116_ap_start");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_ap_done, "grp_encodeToJPG_fu_116_ap_done");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_ap_idle, "grp_encodeToJPG_fu_116_ap_idle");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_ap_ready, "grp_encodeToJPG_fu_116_ap_ready");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_buffer_address0, "grp_encodeToJPG_fu_116_JpegEncoder_buffer_address0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_buffer_ce0, "grp_encodeToJPG_fu_116_JpegEncoder_buffer_ce0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_buffer_we0, "grp_encodeToJPG_fu_116_JpegEncoder_buffer_we0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_buffer_d0, "grp_encodeToJPG_fu_116_JpegEncoder_buffer_d0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_buffer_address1, "grp_encodeToJPG_fu_116_JpegEncoder_buffer_address1");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_buffer_ce1, "grp_encodeToJPG_fu_116_JpegEncoder_buffer_ce1");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_buffer_we1, "grp_encodeToJPG_fu_116_JpegEncoder_buffer_we1");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_buffer_d1, "grp_encodeToJPG_fu_116_JpegEncoder_buffer_d1");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_YTable_address0, "grp_encodeToJPG_fu_116_JpegEncoder_m_YTable_address0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_YTable_ce0, "grp_encodeToJPG_fu_116_JpegEncoder_m_YTable_ce0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_YTable_we0, "grp_encodeToJPG_fu_116_JpegEncoder_m_YTable_we0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_YTable_d0, "grp_encodeToJPG_fu_116_JpegEncoder_m_YTable_d0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_CbCrTable_address0, "grp_encodeToJPG_fu_116_JpegEncoder_m_CbCrTable_address0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_CbCrTable_ce0, "grp_encodeToJPG_fu_116_JpegEncoder_m_CbCrTable_ce0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_CbCrTable_we0, "grp_encodeToJPG_fu_116_JpegEncoder_m_CbCrTable_we0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_CbCrTable_d0, "grp_encodeToJPG_fu_116_JpegEncoder_m_CbCrTable_d0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_Y_DC_Huffman_Table_length_address0, "grp_encodeToJPG_fu_116_JpegEncoder_m_Y_DC_Huffman_Table_length_address0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_Y_DC_Huffman_Table_length_ce0, "grp_encodeToJPG_fu_116_JpegEncoder_m_Y_DC_Huffman_Table_length_ce0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_Y_DC_Huffman_Table_length_we0, "grp_encodeToJPG_fu_116_JpegEncoder_m_Y_DC_Huffman_Table_length_we0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_Y_DC_Huffman_Table_length_d0, "grp_encodeToJPG_fu_116_JpegEncoder_m_Y_DC_Huffman_Table_length_d0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_Y_DC_Huffman_Table_value_address0, "grp_encodeToJPG_fu_116_JpegEncoder_m_Y_DC_Huffman_Table_value_address0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_Y_DC_Huffman_Table_value_ce0, "grp_encodeToJPG_fu_116_JpegEncoder_m_Y_DC_Huffman_Table_value_ce0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_Y_DC_Huffman_Table_value_we0, "grp_encodeToJPG_fu_116_JpegEncoder_m_Y_DC_Huffman_Table_value_we0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_Y_DC_Huffman_Table_value_d0, "grp_encodeToJPG_fu_116_JpegEncoder_m_Y_DC_Huffman_Table_value_d0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_length_address0, "grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_length_address0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_length_ce0, "grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_length_ce0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_length_we0, "grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_length_we0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_length_d0, "grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_length_d0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_length_address1, "grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_length_address1");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_length_ce1, "grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_length_ce1");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_value_address0, "grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_value_address0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_value_ce0, "grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_value_ce0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_value_we0, "grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_value_we0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_value_d0, "grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_value_d0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_value_address1, "grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_value_address1");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_value_ce1, "grp_encodeToJPG_fu_116_JpegEncoder_m_Y_AC_Huffman_Table_value_ce1");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_DC_Huffman_Table_length_address0, "grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_DC_Huffman_Table_length_address0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_DC_Huffman_Table_length_ce0, "grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_DC_Huffman_Table_length_ce0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_DC_Huffman_Table_length_we0, "grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_DC_Huffman_Table_length_we0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_DC_Huffman_Table_length_d0, "grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_DC_Huffman_Table_length_d0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_DC_Huffman_Table_value_address0, "grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_DC_Huffman_Table_value_address0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_DC_Huffman_Table_value_ce0, "grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_DC_Huffman_Table_value_ce0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_DC_Huffman_Table_value_we0, "grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_DC_Huffman_Table_value_we0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_DC_Huffman_Table_value_d0, "grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_DC_Huffman_Table_value_d0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_length_address0, "grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_length_address0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_length_ce0, "grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_length_ce0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_length_we0, "grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_length_we0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_length_d0, "grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_length_d0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_length_address1, "grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_length_address1");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_length_ce1, "grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_length_ce1");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_value_address0, "grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_value_address0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_value_ce0, "grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_value_ce0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_value_we0, "grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_value_we0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_value_d0, "grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_value_d0");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_value_address1, "grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_value_address1");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_value_ce1, "grp_encodeToJPG_fu_116_JpegEncoder_m_CbCr_AC_Huffman_Table_value_ce1");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_rgb_in_TREADY, "grp_encodeToJPG_fu_116_rgb_in_TREADY");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_jpeg_out_TDATA, "grp_encodeToJPG_fu_116_jpeg_out_TDATA");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_jpeg_out_TVALID, "grp_encodeToJPG_fu_116_jpeg_out_TVALID");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_jpeg_out_TREADY, "grp_encodeToJPG_fu_116_jpeg_out_TREADY");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_jpeg_out_TKEEP, "grp_encodeToJPG_fu_116_jpeg_out_TKEEP");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_jpeg_out_TSTRB, "grp_encodeToJPG_fu_116_jpeg_out_TSTRB");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_jpeg_out_TLAST, "grp_encodeToJPG_fu_116_jpeg_out_TLAST");
    sc_trace(mVcdFile, grp_p_write_byte_s_fu_184_ap_start, "grp_p_write_byte_s_fu_184_ap_start");
    sc_trace(mVcdFile, grp_p_write_byte_s_fu_184_ap_done, "grp_p_write_byte_s_fu_184_ap_done");
    sc_trace(mVcdFile, grp_p_write_byte_s_fu_184_ap_idle, "grp_p_write_byte_s_fu_184_ap_idle");
    sc_trace(mVcdFile, grp_p_write_byte_s_fu_184_ap_ready, "grp_p_write_byte_s_fu_184_ap_ready");
    sc_trace(mVcdFile, grp_p_write_byte_s_fu_184_JpegEncoder_outhebyte_last_V_read, "grp_p_write_byte_s_fu_184_JpegEncoder_outhebyte_last_V_read");
    sc_trace(mVcdFile, grp_p_write_byte_s_fu_184_value_r, "grp_p_write_byte_s_fu_184_value_r");
    sc_trace(mVcdFile, grp_p_write_byte_s_fu_184_jpeg_out_TDATA, "grp_p_write_byte_s_fu_184_jpeg_out_TDATA");
    sc_trace(mVcdFile, grp_p_write_byte_s_fu_184_jpeg_out_TVALID, "grp_p_write_byte_s_fu_184_jpeg_out_TVALID");
    sc_trace(mVcdFile, grp_p_write_byte_s_fu_184_jpeg_out_TREADY, "grp_p_write_byte_s_fu_184_jpeg_out_TREADY");
    sc_trace(mVcdFile, grp_p_write_byte_s_fu_184_jpeg_out_TKEEP, "grp_p_write_byte_s_fu_184_jpeg_out_TKEEP");
    sc_trace(mVcdFile, grp_p_write_byte_s_fu_184_jpeg_out_TSTRB, "grp_p_write_byte_s_fu_184_jpeg_out_TSTRB");
    sc_trace(mVcdFile, grp_p_write_byte_s_fu_184_jpeg_out_TLAST, "grp_p_write_byte_s_fu_184_jpeg_out_TLAST");
    sc_trace(mVcdFile, grp_p_write_byte_s_fu_184_ap_return, "grp_p_write_byte_s_fu_184_ap_return");
    sc_trace(mVcdFile, grp_p_write_byte_s_fu_184_ap_ce, "grp_p_write_byte_s_fu_184_ap_ce");
    sc_trace(mVcdFile, grp_encodeToJPG_fu_116_ap_start_reg, "grp_encodeToJPG_fu_116_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("jpeg2.hdltvin.dat");
    mHdltvoutHandle.open("jpeg2.hdltvout.dat");
}

jpeg2::~jpeg2() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete jpeg2_AXILiteS_s_axi_U;
    delete jpeg1_buffer_U;
    delete jpeg1_m_YTable_U;
    delete jpeg1_m_CbCrTable_U;
    delete jpeg1_m_Y_DC_Huffman_U;
    delete jpeg1_m_Y_DC_Huffman_1_U;
    delete jpeg1_m_Y_AC_Huffman_U;
    delete jpeg1_m_Y_AC_Huffman_1_U;
    delete jpeg1_m_CbCr_DC_Huff_U;
    delete jpeg1_m_CbCr_DC_Huff_1_U;
    delete jpeg1_m_CbCr_AC_Huff_U;
    delete jpeg1_m_CbCr_AC_Huff_1_U;
    delete grp_encodeToJPG_fu_116;
    delete grp_p_write_byte_s_fu_184;
}

void jpeg2::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void jpeg2::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        grp_encodeToJPG_fu_116_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            grp_encodeToJPG_fu_116_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_encodeToJPG_fu_116_ap_ready.read())) {
            grp_encodeToJPG_fu_116_ap_start_reg = ap_const_logic_0;
        }
    }
}

void jpeg2::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void jpeg2::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void jpeg2::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void jpeg2::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void jpeg2::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(grp_p_write_byte_s_fu_184_jpeg_out_TDATA_blk_n.read(), ap_const_logic_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void jpeg2::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void jpeg2::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(grp_p_write_byte_s_fu_184_jpeg_out_TDATA_blk_n.read(), ap_const_logic_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void jpeg2::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void jpeg2::thread_grp_encodeToJPG_fu_116_ap_start() {
    grp_encodeToJPG_fu_116_ap_start = grp_encodeToJPG_fu_116_ap_start_reg.read();
}

void jpeg2::thread_grp_encodeToJPG_fu_116_jpeg_out_TREADY() {
    grp_encodeToJPG_fu_116_jpeg_out_TREADY = (jpeg_out_TREADY.read() & ap_CS_fsm_state2.read());
}

void jpeg2::thread_grp_p_write_byte_s_fu_184_JpegEncoder_outhebyte_last_V_read() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        grp_p_write_byte_s_fu_184_JpegEncoder_outhebyte_last_V_read = ap_const_lv1_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        grp_p_write_byte_s_fu_184_JpegEncoder_outhebyte_last_V_read = ap_const_lv1_0;
    } else {
        grp_p_write_byte_s_fu_184_JpegEncoder_outhebyte_last_V_read = "X";
    }
}

void jpeg2::thread_grp_p_write_byte_s_fu_184_ap_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        grp_p_write_byte_s_fu_184_ap_ce = ap_const_logic_1;
    } else {
        grp_p_write_byte_s_fu_184_ap_ce = ap_const_logic_0;
    }
}

void jpeg2::thread_grp_p_write_byte_s_fu_184_ap_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        grp_p_write_byte_s_fu_184_ap_start = ap_const_logic_1;
    } else {
        grp_p_write_byte_s_fu_184_ap_start = ap_const_logic_0;
    }
}

void jpeg2::thread_grp_p_write_byte_s_fu_184_jpeg_out_TREADY() {
    grp_p_write_byte_s_fu_184_jpeg_out_TREADY = ((jpeg_out_TREADY.read() & 
  ap_CS_fsm_state3.read()) | (jpeg_out_TREADY.read() & 
  ap_CS_fsm_state4.read()));
}

void jpeg2::thread_grp_p_write_byte_s_fu_184_value_r() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        grp_p_write_byte_s_fu_184_value_r = ap_const_lv8_D9;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        grp_p_write_byte_s_fu_184_value_r = ap_const_lv8_FF;
    } else {
        grp_p_write_byte_s_fu_184_value_r =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void jpeg2::thread_jpeg_out_TDATA() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, grp_p_write_byte_s_fu_184_jpeg_out_TVALID.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, grp_p_write_byte_s_fu_184_jpeg_out_TVALID.read())))) {
        jpeg_out_TDATA = grp_p_write_byte_s_fu_184_jpeg_out_TDATA.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, grp_encodeToJPG_fu_116_jpeg_out_TVALID.read()))) {
        jpeg_out_TDATA = grp_encodeToJPG_fu_116_jpeg_out_TDATA.read();
    } else {
        jpeg_out_TDATA =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void jpeg2::thread_jpeg_out_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        jpeg_out_TDATA_blk_n = grp_p_write_byte_s_fu_184_jpeg_out_TDATA_blk_n.read();
    } else {
        jpeg_out_TDATA_blk_n = ap_const_logic_1;
    }
}

void jpeg2::thread_jpeg_out_TKEEP() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, grp_p_write_byte_s_fu_184_jpeg_out_TVALID.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, grp_p_write_byte_s_fu_184_jpeg_out_TVALID.read())))) {
        jpeg_out_TKEEP = grp_p_write_byte_s_fu_184_jpeg_out_TKEEP.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, grp_encodeToJPG_fu_116_jpeg_out_TVALID.read()))) {
        jpeg_out_TKEEP = grp_encodeToJPG_fu_116_jpeg_out_TKEEP.read();
    } else {
        jpeg_out_TKEEP = "X";
    }
}

void jpeg2::thread_jpeg_out_TLAST() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, grp_p_write_byte_s_fu_184_jpeg_out_TVALID.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, grp_p_write_byte_s_fu_184_jpeg_out_TVALID.read())))) {
        jpeg_out_TLAST = grp_p_write_byte_s_fu_184_jpeg_out_TLAST.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, grp_encodeToJPG_fu_116_jpeg_out_TVALID.read()))) {
        jpeg_out_TLAST = grp_encodeToJPG_fu_116_jpeg_out_TLAST.read();
    } else {
        jpeg_out_TLAST = "X";
    }
}

void jpeg2::thread_jpeg_out_TSTRB() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, grp_p_write_byte_s_fu_184_jpeg_out_TVALID.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, grp_p_write_byte_s_fu_184_jpeg_out_TVALID.read())))) {
        jpeg_out_TSTRB = grp_p_write_byte_s_fu_184_jpeg_out_TSTRB.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, grp_encodeToJPG_fu_116_jpeg_out_TVALID.read()))) {
        jpeg_out_TSTRB = grp_encodeToJPG_fu_116_jpeg_out_TSTRB.read();
    } else {
        jpeg_out_TSTRB = "X";
    }
}

void jpeg2::thread_jpeg_out_TVALID() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        jpeg_out_TVALID = grp_p_write_byte_s_fu_184_jpeg_out_TVALID.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        jpeg_out_TVALID = grp_encodeToJPG_fu_116_jpeg_out_TVALID.read();
    } else {
        jpeg_out_TVALID = ap_const_logic_0;
    }
}

void jpeg2::thread_rgb_in_TREADY() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        rgb_in_TREADY = grp_encodeToJPG_fu_116_rgb_in_TREADY.read();
    } else {
        rgb_in_TREADY = ap_const_logic_0;
    }
}

void jpeg2::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(grp_encodeToJPG_fu_116_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(grp_p_write_byte_s_fu_184_jpeg_out_TDATA_blk_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(grp_p_write_byte_s_fu_184_jpeg_out_TDATA_blk_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<4>) ("XXXX");
            break;
    }
}

void jpeg2::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"rgb_in_TDATA\" :  \"" << rgb_in_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"rgb_in_TVALID\" :  \"" << rgb_in_TVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"rgb_in_TREADY\" :  \"" << rgb_in_TREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"rgb_in_TKEEP\" :  \"" << rgb_in_TKEEP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"rgb_in_TSTRB\" :  \"" << rgb_in_TSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"rgb_in_TLAST\" :  \"" << rgb_in_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"jpeg_out_TDATA\" :  \"" << jpeg_out_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"jpeg_out_TVALID\" :  \"" << jpeg_out_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"jpeg_out_TREADY\" :  \"" << jpeg_out_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"jpeg_out_TKEEP\" :  \"" << jpeg_out_TKEEP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"jpeg_out_TSTRB\" :  \"" << jpeg_out_TSTRB.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"jpeg_out_TLAST\" :  \"" << jpeg_out_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_AWVALID\" :  \"" << s_axi_AXILiteS_AWVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_AWREADY\" :  \"" << s_axi_AXILiteS_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_AWADDR\" :  \"" << s_axi_AXILiteS_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WVALID\" :  \"" << s_axi_AXILiteS_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_WREADY\" :  \"" << s_axi_AXILiteS_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WDATA\" :  \"" << s_axi_AXILiteS_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WSTRB\" :  \"" << s_axi_AXILiteS_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARVALID\" :  \"" << s_axi_AXILiteS_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_ARREADY\" :  \"" << s_axi_AXILiteS_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARADDR\" :  \"" << s_axi_AXILiteS_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RVALID\" :  \"" << s_axi_AXILiteS_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_RREADY\" :  \"" << s_axi_AXILiteS_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RDATA\" :  \"" << s_axi_AXILiteS_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RRESP\" :  \"" << s_axi_AXILiteS_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BVALID\" :  \"" << s_axi_AXILiteS_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_BREADY\" :  \"" << s_axi_AXILiteS_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BRESP\" :  \"" << s_axi_AXILiteS_BRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"interrupt\" :  \"" << interrupt.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

