// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "readFromBMP.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic readFromBMP::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic readFromBMP::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<14> readFromBMP::ap_ST_fsm_state1 = "1";
const sc_lv<14> readFromBMP::ap_ST_fsm_state2 = "10";
const sc_lv<14> readFromBMP::ap_ST_fsm_state3 = "100";
const sc_lv<14> readFromBMP::ap_ST_fsm_state4 = "1000";
const sc_lv<14> readFromBMP::ap_ST_fsm_state5 = "10000";
const sc_lv<14> readFromBMP::ap_ST_fsm_state6 = "100000";
const sc_lv<14> readFromBMP::ap_ST_fsm_state7 = "1000000";
const sc_lv<14> readFromBMP::ap_ST_fsm_state8 = "10000000";
const sc_lv<14> readFromBMP::ap_ST_fsm_state9 = "100000000";
const sc_lv<14> readFromBMP::ap_ST_fsm_state10 = "1000000000";
const sc_lv<14> readFromBMP::ap_ST_fsm_state11 = "10000000000";
const sc_lv<14> readFromBMP::ap_ST_fsm_state12 = "100000000000";
const sc_lv<14> readFromBMP::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<14> readFromBMP::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<32> readFromBMP::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> readFromBMP::ap_const_lv32_2 = "10";
const sc_lv<32> readFromBMP::ap_const_lv32_3 = "11";
const sc_lv<32> readFromBMP::ap_const_lv32_5 = "101";
const sc_lv<32> readFromBMP::ap_const_lv32_6 = "110";
const sc_lv<32> readFromBMP::ap_const_lv32_8 = "1000";
const sc_lv<32> readFromBMP::ap_const_lv32_9 = "1001";
const sc_lv<32> readFromBMP::ap_const_lv32_B = "1011";
const sc_lv<32> readFromBMP::ap_const_lv32_C = "1100";
const sc_lv<32> readFromBMP::ap_const_lv32_1 = "1";
const sc_lv<1> readFromBMP::ap_const_lv1_0 = "0";
const sc_lv<32> readFromBMP::ap_const_lv32_4 = "100";
const sc_lv<32> readFromBMP::ap_const_lv32_7 = "111";
const sc_lv<32> readFromBMP::ap_const_lv32_A = "1010";
const sc_lv<13> readFromBMP::ap_const_lv13_0 = "0000000000000";
const sc_lv<32> readFromBMP::ap_const_lv32_D = "1101";
const sc_lv<32> readFromBMP::ap_const_lv32_10 = "10000";
const sc_lv<32> readFromBMP::ap_const_lv32_17 = "10111";
const sc_lv<32> readFromBMP::ap_const_lv32_F = "1111";
const sc_lv<13> readFromBMP::ap_const_lv13_1400 = "1010000000000";
const sc_lv<2> readFromBMP::ap_const_lv2_0 = "00";
const sc_lv<13> readFromBMP::ap_const_lv13_1 = "1";
const sc_lv<16> readFromBMP::ap_const_lv16_2 = "10";
const sc_lv<16> readFromBMP::ap_const_lv16_1 = "1";
const sc_lv<13> readFromBMP::ap_const_lv13_2 = "10";
const sc_lv<13> readFromBMP::ap_const_lv13_3 = "11";
const sc_lv<13> readFromBMP::ap_const_lv13_4 = "100";
const sc_lv<13> readFromBMP::ap_const_lv13_5 = "101";
const sc_lv<13> readFromBMP::ap_const_lv13_6 = "110";
const sc_lv<13> readFromBMP::ap_const_lv13_7 = "111";
const sc_lv<13> readFromBMP::ap_const_lv13_8 = "1000";
const sc_lv<1> readFromBMP::ap_const_lv1_1 = "1";
const bool readFromBMP::ap_const_boolean_1 = true;

readFromBMP::readFromBMP(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_JpegEncoder_buffer_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( zext_ln166_fu_358_p1 );
    sensitive << ( zext_ln168_fu_415_p1 );
    sensitive << ( zext_ln167_1_fu_445_p1 );
    sensitive << ( zext_ln166_2_fu_489_p1 );
    sensitive << ( zext_ln168_2_fu_545_p1 );
    sensitive << ( zext_ln167_3_fu_575_p1 );
    sensitive << ( zext_ln166_4_fu_619_p1 );
    sensitive << ( zext_ln168_4_fu_676_p1 );
    sensitive << ( zext_ln167_5_fu_706_p1 );
    sensitive << ( zext_ln166_6_fu_750_p1 );
    sensitive << ( zext_ln168_6_fu_812_p1 );
    sensitive << ( zext_ln167_7_fu_842_p1 );

    SC_METHOD(thread_JpegEncoder_buffer_address1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( zext_ln167_fu_369_p1 );
    sensitive << ( zext_ln166_1_fu_423_p1 );
    sensitive << ( zext_ln168_1_fu_453_p1 );
    sensitive << ( zext_ln167_2_fu_500_p1 );
    sensitive << ( zext_ln166_3_fu_553_p1 );
    sensitive << ( zext_ln168_3_fu_583_p1 );
    sensitive << ( zext_ln167_4_fu_630_p1 );
    sensitive << ( zext_ln166_5_fu_684_p1 );
    sensitive << ( zext_ln168_5_fu_714_p1 );
    sensitive << ( zext_ln167_6_fu_761_p1 );
    sensitive << ( zext_ln166_7_fu_820_p1 );
    sensitive << ( zext_ln168_7_fu_850_p1 );

    SC_METHOD(thread_JpegEncoder_buffer_ce0);
    sensitive << ( rgb_in_TVALID );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_JpegEncoder_buffer_ce1);
    sensitive << ( rgb_in_TVALID );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_JpegEncoder_buffer_d0);
    sensitive << ( rgb_in_TDATA );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( reg_322 );
    sensitive << ( trunc_ln168_reg_864 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( trunc_ln168_2_reg_897 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( trunc_ln168_4_reg_935 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( trunc_ln168_6_reg_968 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_JpegEncoder_buffer_d1);
    sensitive << ( rgb_in_TDATA );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( trunc_ln168_1_reg_881 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( trunc_ln168_3_reg_919 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( trunc_ln168_5_reg_952 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( trunc_ln168_7_reg_995 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_JpegEncoder_buffer_we0);
    sensitive << ( rgb_in_TVALID );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_JpegEncoder_buffer_we1);
    sensitive << ( rgb_in_TVALID );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_add_ln163_fu_803_p2);
    sensitive << ( i_0_0_reg_283 );

    SC_METHOD(thread_add_ln167_1_fu_558_p2);
    sensitive << ( sub_ln166_3_reg_907 );

    SC_METHOD(thread_add_ln167_2_fu_689_p2);
    sensitive << ( sub_ln166_5_reg_940 );

    SC_METHOD(thread_add_ln167_3_fu_825_p2);
    sensitive << ( sub_ln166_7_reg_978 );

    SC_METHOD(thread_add_ln167_fu_428_p2);
    sensitive << ( sub_ln166_1_reg_869 );

    SC_METHOD(thread_add_ln168_1_fu_509_p2);
    sensitive << ( sub_ln166_2_reg_891 );

    SC_METHOD(thread_add_ln168_2_fu_567_p2);
    sensitive << ( sub_ln166_3_reg_907 );

    SC_METHOD(thread_add_ln168_3_fu_698_p2);
    sensitive << ( sub_ln166_5_reg_940 );

    SC_METHOD(thread_add_ln168_4_fu_770_p2);
    sensitive << ( sub_ln166_6_reg_962 );

    SC_METHOD(thread_add_ln168_5_fu_834_p2);
    sensitive << ( sub_ln166_7_reg_978 );

    SC_METHOD(thread_add_ln168_fu_437_p2);
    sensitive << ( sub_ln166_1_reg_869 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln163_fu_331_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln163_fu_331_p2 );

    SC_METHOD(thread_i_0_0_cast8_fu_327_p1);
    sensitive << ( i_0_0_reg_283 );

    SC_METHOD(thread_icmp_ln163_fu_331_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_0_reg_283 );

    SC_METHOD(thread_or_ln163_1_fu_458_p2);
    sensitive << ( i_0_0_reg_283 );

    SC_METHOD(thread_or_ln163_2_fu_514_p2);
    sensitive << ( i_0_0_reg_283 );

    SC_METHOD(thread_or_ln163_3_fu_588_p2);
    sensitive << ( i_0_0_reg_283 );

    SC_METHOD(thread_or_ln163_4_fu_639_p2);
    sensitive << ( i_0_0_reg_283 );

    SC_METHOD(thread_or_ln163_5_fu_719_p2);
    sensitive << ( i_0_0_reg_283 );

    SC_METHOD(thread_or_ln163_6_fu_775_p2);
    sensitive << ( i_0_0_reg_283 );

    SC_METHOD(thread_or_ln163_fu_378_p2);
    sensitive << ( i_0_0_reg_283 );

    SC_METHOD(thread_or_ln167_1_fu_494_p2);
    sensitive << ( sext_ln166_2_fu_486_p1 );

    SC_METHOD(thread_or_ln167_2_fu_624_p2);
    sensitive << ( sext_ln166_4_fu_616_p1 );

    SC_METHOD(thread_or_ln167_3_fu_755_p2);
    sensitive << ( sext_ln166_6_fu_747_p1 );

    SC_METHOD(thread_or_ln167_fu_363_p2);
    sensitive << ( sext_ln166_fu_355_p1 );

    SC_METHOD(thread_or_ln168_1_fu_667_p2);
    sensitive << ( sub_ln166_4_reg_929 );

    SC_METHOD(thread_or_ln168_fu_406_p2);
    sensitive << ( sub_ln166_reg_858 );

    SC_METHOD(thread_rgb_in_TDATA_blk_n);
    sensitive << ( rgb_in_TVALID );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_rgb_in_TREADY);
    sensitive << ( rgb_in_TVALID );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_sext_ln166_1_fu_420_p1);
    sensitive << ( sub_ln166_1_reg_869 );

    SC_METHOD(thread_sext_ln166_2_fu_486_p1);
    sensitive << ( sub_ln166_2_reg_891 );

    SC_METHOD(thread_sext_ln166_3_fu_550_p1);
    sensitive << ( sub_ln166_3_reg_907 );

    SC_METHOD(thread_sext_ln166_4_fu_616_p1);
    sensitive << ( sub_ln166_4_reg_929 );

    SC_METHOD(thread_sext_ln166_5_fu_681_p1);
    sensitive << ( sub_ln166_5_reg_940 );

    SC_METHOD(thread_sext_ln166_6_fu_747_p1);
    sensitive << ( sub_ln166_6_reg_962 );

    SC_METHOD(thread_sext_ln166_7_fu_817_p1);
    sensitive << ( sub_ln166_7_reg_978 );

    SC_METHOD(thread_sext_ln166_fu_355_p1);
    sensitive << ( sub_ln166_reg_858 );

    SC_METHOD(thread_sext_ln167_1_fu_572_p1);
    sensitive << ( add_ln167_1_reg_914 );

    SC_METHOD(thread_sext_ln167_2_fu_703_p1);
    sensitive << ( add_ln167_2_reg_947 );

    SC_METHOD(thread_sext_ln167_3_fu_839_p1);
    sensitive << ( add_ln167_3_reg_990 );

    SC_METHOD(thread_sext_ln167_fu_442_p1);
    sensitive << ( add_ln167_reg_876 );

    SC_METHOD(thread_sext_ln168_1_fu_450_p1);
    sensitive << ( add_ln168_reg_886 );

    SC_METHOD(thread_sext_ln168_2_fu_542_p1);
    sensitive << ( add_ln168_1_reg_902 );

    SC_METHOD(thread_sext_ln168_3_fu_580_p1);
    sensitive << ( add_ln168_2_reg_924 );

    SC_METHOD(thread_sext_ln168_4_fu_672_p1);
    sensitive << ( or_ln168_1_fu_667_p2 );

    SC_METHOD(thread_sext_ln168_5_fu_711_p1);
    sensitive << ( add_ln168_3_reg_957 );

    SC_METHOD(thread_sext_ln168_6_fu_809_p1);
    sensitive << ( add_ln168_4_reg_973 );

    SC_METHOD(thread_sext_ln168_7_fu_847_p1);
    sensitive << ( add_ln168_5_reg_1000 );

    SC_METHOD(thread_sext_ln168_fu_411_p1);
    sensitive << ( or_ln168_fu_406_p2 );

    SC_METHOD(thread_shl_ln166_1_fu_388_p3);
    sensitive << ( or_ln163_fu_378_p2 );

    SC_METHOD(thread_shl_ln166_2_fu_468_p3);
    sensitive << ( or_ln163_1_fu_458_p2 );

    SC_METHOD(thread_shl_ln166_3_fu_524_p3);
    sensitive << ( or_ln163_2_fu_514_p2 );

    SC_METHOD(thread_shl_ln166_4_fu_598_p3);
    sensitive << ( or_ln163_3_fu_588_p2 );

    SC_METHOD(thread_shl_ln166_5_fu_649_p3);
    sensitive << ( or_ln163_4_fu_639_p2 );

    SC_METHOD(thread_shl_ln166_6_fu_729_p3);
    sensitive << ( or_ln163_5_fu_719_p2 );

    SC_METHOD(thread_shl_ln166_7_fu_785_p3);
    sensitive << ( or_ln163_6_fu_775_p2 );

    SC_METHOD(thread_shl_ln_fu_337_p3);
    sensitive << ( i_0_0_reg_283 );

    SC_METHOD(thread_sub_ln166_1_fu_400_p2);
    sensitive << ( zext_ln166_9_fu_396_p1 );
    sensitive << ( zext_ln163_fu_384_p1 );

    SC_METHOD(thread_sub_ln166_2_fu_480_p2);
    sensitive << ( zext_ln166_10_fu_476_p1 );
    sensitive << ( zext_ln163_1_fu_464_p1 );

    SC_METHOD(thread_sub_ln166_3_fu_536_p2);
    sensitive << ( zext_ln166_11_fu_532_p1 );
    sensitive << ( zext_ln163_2_fu_520_p1 );

    SC_METHOD(thread_sub_ln166_4_fu_610_p2);
    sensitive << ( zext_ln166_12_fu_606_p1 );
    sensitive << ( zext_ln163_3_fu_594_p1 );

    SC_METHOD(thread_sub_ln166_5_fu_661_p2);
    sensitive << ( zext_ln166_13_fu_657_p1 );
    sensitive << ( zext_ln163_4_fu_645_p1 );

    SC_METHOD(thread_sub_ln166_6_fu_741_p2);
    sensitive << ( zext_ln166_14_fu_737_p1 );
    sensitive << ( zext_ln163_5_fu_725_p1 );

    SC_METHOD(thread_sub_ln166_7_fu_797_p2);
    sensitive << ( zext_ln166_15_fu_793_p1 );
    sensitive << ( zext_ln163_6_fu_781_p1 );

    SC_METHOD(thread_sub_ln166_fu_349_p2);
    sensitive << ( zext_ln166_8_fu_345_p1 );
    sensitive << ( i_0_0_cast8_fu_327_p1 );

    SC_METHOD(thread_trunc_ln168_1_fu_433_p1);
    sensitive << ( rgb_in_TDATA );

    SC_METHOD(thread_trunc_ln168_2_fu_505_p1);
    sensitive << ( rgb_in_TDATA );

    SC_METHOD(thread_trunc_ln168_3_fu_563_p1);
    sensitive << ( rgb_in_TDATA );

    SC_METHOD(thread_trunc_ln168_4_fu_635_p1);
    sensitive << ( rgb_in_TDATA );

    SC_METHOD(thread_trunc_ln168_5_fu_694_p1);
    sensitive << ( rgb_in_TDATA );

    SC_METHOD(thread_trunc_ln168_6_fu_766_p1);
    sensitive << ( rgb_in_TDATA );

    SC_METHOD(thread_trunc_ln168_7_fu_830_p1);
    sensitive << ( rgb_in_TDATA );

    SC_METHOD(thread_trunc_ln168_fu_374_p1);
    sensitive << ( rgb_in_TDATA );

    SC_METHOD(thread_zext_ln163_1_fu_464_p1);
    sensitive << ( or_ln163_1_fu_458_p2 );

    SC_METHOD(thread_zext_ln163_2_fu_520_p1);
    sensitive << ( or_ln163_2_fu_514_p2 );

    SC_METHOD(thread_zext_ln163_3_fu_594_p1);
    sensitive << ( or_ln163_3_fu_588_p2 );

    SC_METHOD(thread_zext_ln163_4_fu_645_p1);
    sensitive << ( or_ln163_4_fu_639_p2 );

    SC_METHOD(thread_zext_ln163_5_fu_725_p1);
    sensitive << ( or_ln163_5_fu_719_p2 );

    SC_METHOD(thread_zext_ln163_6_fu_781_p1);
    sensitive << ( or_ln163_6_fu_775_p2 );

    SC_METHOD(thread_zext_ln163_fu_384_p1);
    sensitive << ( or_ln163_fu_378_p2 );

    SC_METHOD(thread_zext_ln166_10_fu_476_p1);
    sensitive << ( shl_ln166_2_fu_468_p3 );

    SC_METHOD(thread_zext_ln166_11_fu_532_p1);
    sensitive << ( shl_ln166_3_fu_524_p3 );

    SC_METHOD(thread_zext_ln166_12_fu_606_p1);
    sensitive << ( shl_ln166_4_fu_598_p3 );

    SC_METHOD(thread_zext_ln166_13_fu_657_p1);
    sensitive << ( shl_ln166_5_fu_649_p3 );

    SC_METHOD(thread_zext_ln166_14_fu_737_p1);
    sensitive << ( shl_ln166_6_fu_729_p3 );

    SC_METHOD(thread_zext_ln166_15_fu_793_p1);
    sensitive << ( shl_ln166_7_fu_785_p3 );

    SC_METHOD(thread_zext_ln166_1_fu_423_p1);
    sensitive << ( sext_ln166_1_fu_420_p1 );

    SC_METHOD(thread_zext_ln166_2_fu_489_p1);
    sensitive << ( sext_ln166_2_fu_486_p1 );

    SC_METHOD(thread_zext_ln166_3_fu_553_p1);
    sensitive << ( sext_ln166_3_fu_550_p1 );

    SC_METHOD(thread_zext_ln166_4_fu_619_p1);
    sensitive << ( sext_ln166_4_fu_616_p1 );

    SC_METHOD(thread_zext_ln166_5_fu_684_p1);
    sensitive << ( sext_ln166_5_fu_681_p1 );

    SC_METHOD(thread_zext_ln166_6_fu_750_p1);
    sensitive << ( sext_ln166_6_fu_747_p1 );

    SC_METHOD(thread_zext_ln166_7_fu_820_p1);
    sensitive << ( sext_ln166_7_fu_817_p1 );

    SC_METHOD(thread_zext_ln166_8_fu_345_p1);
    sensitive << ( shl_ln_fu_337_p3 );

    SC_METHOD(thread_zext_ln166_9_fu_396_p1);
    sensitive << ( shl_ln166_1_fu_388_p3 );

    SC_METHOD(thread_zext_ln166_fu_358_p1);
    sensitive << ( sext_ln166_fu_355_p1 );

    SC_METHOD(thread_zext_ln167_1_fu_445_p1);
    sensitive << ( sext_ln167_fu_442_p1 );

    SC_METHOD(thread_zext_ln167_2_fu_500_p1);
    sensitive << ( or_ln167_1_fu_494_p2 );

    SC_METHOD(thread_zext_ln167_3_fu_575_p1);
    sensitive << ( sext_ln167_1_fu_572_p1 );

    SC_METHOD(thread_zext_ln167_4_fu_630_p1);
    sensitive << ( or_ln167_2_fu_624_p2 );

    SC_METHOD(thread_zext_ln167_5_fu_706_p1);
    sensitive << ( sext_ln167_2_fu_703_p1 );

    SC_METHOD(thread_zext_ln167_6_fu_761_p1);
    sensitive << ( or_ln167_3_fu_755_p2 );

    SC_METHOD(thread_zext_ln167_7_fu_842_p1);
    sensitive << ( sext_ln167_3_fu_839_p1 );

    SC_METHOD(thread_zext_ln167_fu_369_p1);
    sensitive << ( or_ln167_fu_363_p2 );

    SC_METHOD(thread_zext_ln168_1_fu_453_p1);
    sensitive << ( sext_ln168_1_fu_450_p1 );

    SC_METHOD(thread_zext_ln168_2_fu_545_p1);
    sensitive << ( sext_ln168_2_fu_542_p1 );

    SC_METHOD(thread_zext_ln168_3_fu_583_p1);
    sensitive << ( sext_ln168_3_fu_580_p1 );

    SC_METHOD(thread_zext_ln168_4_fu_676_p1);
    sensitive << ( sext_ln168_4_fu_672_p1 );

    SC_METHOD(thread_zext_ln168_5_fu_714_p1);
    sensitive << ( sext_ln168_5_fu_711_p1 );

    SC_METHOD(thread_zext_ln168_6_fu_812_p1);
    sensitive << ( sext_ln168_6_fu_809_p1 );

    SC_METHOD(thread_zext_ln168_7_fu_850_p1);
    sensitive << ( sext_ln168_7_fu_847_p1 );

    SC_METHOD(thread_zext_ln168_fu_415_p1);
    sensitive << ( sext_ln168_fu_411_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( rgb_in_TVALID );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln163_fu_331_p2 );

    ap_CS_fsm = "00000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "readFromBMP_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, JpegEncoder_buffer_address0, "(port)JpegEncoder_buffer_address0");
    sc_trace(mVcdFile, JpegEncoder_buffer_ce0, "(port)JpegEncoder_buffer_ce0");
    sc_trace(mVcdFile, JpegEncoder_buffer_we0, "(port)JpegEncoder_buffer_we0");
    sc_trace(mVcdFile, JpegEncoder_buffer_d0, "(port)JpegEncoder_buffer_d0");
    sc_trace(mVcdFile, JpegEncoder_buffer_address1, "(port)JpegEncoder_buffer_address1");
    sc_trace(mVcdFile, JpegEncoder_buffer_ce1, "(port)JpegEncoder_buffer_ce1");
    sc_trace(mVcdFile, JpegEncoder_buffer_we1, "(port)JpegEncoder_buffer_we1");
    sc_trace(mVcdFile, JpegEncoder_buffer_d1, "(port)JpegEncoder_buffer_d1");
    sc_trace(mVcdFile, rgb_in_TDATA, "(port)rgb_in_TDATA");
    sc_trace(mVcdFile, rgb_in_TVALID, "(port)rgb_in_TVALID");
    sc_trace(mVcdFile, rgb_in_TREADY, "(port)rgb_in_TREADY");
    sc_trace(mVcdFile, rgb_in_TKEEP, "(port)rgb_in_TKEEP");
    sc_trace(mVcdFile, rgb_in_TSTRB, "(port)rgb_in_TSTRB");
    sc_trace(mVcdFile, rgb_in_TLAST, "(port)rgb_in_TLAST");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, rgb_in_TDATA_blk_n, "rgb_in_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, reg_322, "reg_322");
    sc_trace(mVcdFile, sub_ln166_fu_349_p2, "sub_ln166_fu_349_p2");
    sc_trace(mVcdFile, sub_ln166_reg_858, "sub_ln166_reg_858");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, icmp_ln163_fu_331_p2, "icmp_ln163_fu_331_p2");
    sc_trace(mVcdFile, trunc_ln168_fu_374_p1, "trunc_ln168_fu_374_p1");
    sc_trace(mVcdFile, trunc_ln168_reg_864, "trunc_ln168_reg_864");
    sc_trace(mVcdFile, sub_ln166_1_fu_400_p2, "sub_ln166_1_fu_400_p2");
    sc_trace(mVcdFile, sub_ln166_1_reg_869, "sub_ln166_1_reg_869");
    sc_trace(mVcdFile, add_ln167_fu_428_p2, "add_ln167_fu_428_p2");
    sc_trace(mVcdFile, add_ln167_reg_876, "add_ln167_reg_876");
    sc_trace(mVcdFile, trunc_ln168_1_fu_433_p1, "trunc_ln168_1_fu_433_p1");
    sc_trace(mVcdFile, trunc_ln168_1_reg_881, "trunc_ln168_1_reg_881");
    sc_trace(mVcdFile, add_ln168_fu_437_p2, "add_ln168_fu_437_p2");
    sc_trace(mVcdFile, add_ln168_reg_886, "add_ln168_reg_886");
    sc_trace(mVcdFile, sub_ln166_2_fu_480_p2, "sub_ln166_2_fu_480_p2");
    sc_trace(mVcdFile, sub_ln166_2_reg_891, "sub_ln166_2_reg_891");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, trunc_ln168_2_fu_505_p1, "trunc_ln168_2_fu_505_p1");
    sc_trace(mVcdFile, trunc_ln168_2_reg_897, "trunc_ln168_2_reg_897");
    sc_trace(mVcdFile, add_ln168_1_fu_509_p2, "add_ln168_1_fu_509_p2");
    sc_trace(mVcdFile, add_ln168_1_reg_902, "add_ln168_1_reg_902");
    sc_trace(mVcdFile, sub_ln166_3_fu_536_p2, "sub_ln166_3_fu_536_p2");
    sc_trace(mVcdFile, sub_ln166_3_reg_907, "sub_ln166_3_reg_907");
    sc_trace(mVcdFile, add_ln167_1_fu_558_p2, "add_ln167_1_fu_558_p2");
    sc_trace(mVcdFile, add_ln167_1_reg_914, "add_ln167_1_reg_914");
    sc_trace(mVcdFile, trunc_ln168_3_fu_563_p1, "trunc_ln168_3_fu_563_p1");
    sc_trace(mVcdFile, trunc_ln168_3_reg_919, "trunc_ln168_3_reg_919");
    sc_trace(mVcdFile, add_ln168_2_fu_567_p2, "add_ln168_2_fu_567_p2");
    sc_trace(mVcdFile, add_ln168_2_reg_924, "add_ln168_2_reg_924");
    sc_trace(mVcdFile, sub_ln166_4_fu_610_p2, "sub_ln166_4_fu_610_p2");
    sc_trace(mVcdFile, sub_ln166_4_reg_929, "sub_ln166_4_reg_929");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, trunc_ln168_4_fu_635_p1, "trunc_ln168_4_fu_635_p1");
    sc_trace(mVcdFile, trunc_ln168_4_reg_935, "trunc_ln168_4_reg_935");
    sc_trace(mVcdFile, sub_ln166_5_fu_661_p2, "sub_ln166_5_fu_661_p2");
    sc_trace(mVcdFile, sub_ln166_5_reg_940, "sub_ln166_5_reg_940");
    sc_trace(mVcdFile, add_ln167_2_fu_689_p2, "add_ln167_2_fu_689_p2");
    sc_trace(mVcdFile, add_ln167_2_reg_947, "add_ln167_2_reg_947");
    sc_trace(mVcdFile, trunc_ln168_5_fu_694_p1, "trunc_ln168_5_fu_694_p1");
    sc_trace(mVcdFile, trunc_ln168_5_reg_952, "trunc_ln168_5_reg_952");
    sc_trace(mVcdFile, add_ln168_3_fu_698_p2, "add_ln168_3_fu_698_p2");
    sc_trace(mVcdFile, add_ln168_3_reg_957, "add_ln168_3_reg_957");
    sc_trace(mVcdFile, sub_ln166_6_fu_741_p2, "sub_ln166_6_fu_741_p2");
    sc_trace(mVcdFile, sub_ln166_6_reg_962, "sub_ln166_6_reg_962");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, trunc_ln168_6_fu_766_p1, "trunc_ln168_6_fu_766_p1");
    sc_trace(mVcdFile, trunc_ln168_6_reg_968, "trunc_ln168_6_reg_968");
    sc_trace(mVcdFile, add_ln168_4_fu_770_p2, "add_ln168_4_fu_770_p2");
    sc_trace(mVcdFile, add_ln168_4_reg_973, "add_ln168_4_reg_973");
    sc_trace(mVcdFile, sub_ln166_7_fu_797_p2, "sub_ln166_7_fu_797_p2");
    sc_trace(mVcdFile, sub_ln166_7_reg_978, "sub_ln166_7_reg_978");
    sc_trace(mVcdFile, add_ln163_fu_803_p2, "add_ln163_fu_803_p2");
    sc_trace(mVcdFile, add_ln163_reg_985, "add_ln163_reg_985");
    sc_trace(mVcdFile, add_ln167_3_fu_825_p2, "add_ln167_3_fu_825_p2");
    sc_trace(mVcdFile, add_ln167_3_reg_990, "add_ln167_3_reg_990");
    sc_trace(mVcdFile, trunc_ln168_7_fu_830_p1, "trunc_ln168_7_fu_830_p1");
    sc_trace(mVcdFile, trunc_ln168_7_reg_995, "trunc_ln168_7_reg_995");
    sc_trace(mVcdFile, add_ln168_5_fu_834_p2, "add_ln168_5_fu_834_p2");
    sc_trace(mVcdFile, add_ln168_5_reg_1000, "add_ln168_5_reg_1000");
    sc_trace(mVcdFile, i_0_0_reg_283, "i_0_0_reg_283");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, zext_ln166_fu_358_p1, "zext_ln166_fu_358_p1");
    sc_trace(mVcdFile, zext_ln167_fu_369_p1, "zext_ln167_fu_369_p1");
    sc_trace(mVcdFile, zext_ln168_fu_415_p1, "zext_ln168_fu_415_p1");
    sc_trace(mVcdFile, zext_ln166_1_fu_423_p1, "zext_ln166_1_fu_423_p1");
    sc_trace(mVcdFile, zext_ln167_1_fu_445_p1, "zext_ln167_1_fu_445_p1");
    sc_trace(mVcdFile, zext_ln168_1_fu_453_p1, "zext_ln168_1_fu_453_p1");
    sc_trace(mVcdFile, zext_ln166_2_fu_489_p1, "zext_ln166_2_fu_489_p1");
    sc_trace(mVcdFile, zext_ln167_2_fu_500_p1, "zext_ln167_2_fu_500_p1");
    sc_trace(mVcdFile, zext_ln168_2_fu_545_p1, "zext_ln168_2_fu_545_p1");
    sc_trace(mVcdFile, zext_ln166_3_fu_553_p1, "zext_ln166_3_fu_553_p1");
    sc_trace(mVcdFile, zext_ln167_3_fu_575_p1, "zext_ln167_3_fu_575_p1");
    sc_trace(mVcdFile, zext_ln168_3_fu_583_p1, "zext_ln168_3_fu_583_p1");
    sc_trace(mVcdFile, zext_ln166_4_fu_619_p1, "zext_ln166_4_fu_619_p1");
    sc_trace(mVcdFile, zext_ln167_4_fu_630_p1, "zext_ln167_4_fu_630_p1");
    sc_trace(mVcdFile, zext_ln168_4_fu_676_p1, "zext_ln168_4_fu_676_p1");
    sc_trace(mVcdFile, zext_ln166_5_fu_684_p1, "zext_ln166_5_fu_684_p1");
    sc_trace(mVcdFile, zext_ln167_5_fu_706_p1, "zext_ln167_5_fu_706_p1");
    sc_trace(mVcdFile, zext_ln168_5_fu_714_p1, "zext_ln168_5_fu_714_p1");
    sc_trace(mVcdFile, zext_ln166_6_fu_750_p1, "zext_ln166_6_fu_750_p1");
    sc_trace(mVcdFile, zext_ln167_6_fu_761_p1, "zext_ln167_6_fu_761_p1");
    sc_trace(mVcdFile, zext_ln168_6_fu_812_p1, "zext_ln168_6_fu_812_p1");
    sc_trace(mVcdFile, zext_ln166_7_fu_820_p1, "zext_ln166_7_fu_820_p1");
    sc_trace(mVcdFile, zext_ln167_7_fu_842_p1, "zext_ln167_7_fu_842_p1");
    sc_trace(mVcdFile, zext_ln168_7_fu_850_p1, "zext_ln168_7_fu_850_p1");
    sc_trace(mVcdFile, shl_ln_fu_337_p3, "shl_ln_fu_337_p3");
    sc_trace(mVcdFile, zext_ln166_8_fu_345_p1, "zext_ln166_8_fu_345_p1");
    sc_trace(mVcdFile, i_0_0_cast8_fu_327_p1, "i_0_0_cast8_fu_327_p1");
    sc_trace(mVcdFile, sext_ln166_fu_355_p1, "sext_ln166_fu_355_p1");
    sc_trace(mVcdFile, or_ln167_fu_363_p2, "or_ln167_fu_363_p2");
    sc_trace(mVcdFile, or_ln163_fu_378_p2, "or_ln163_fu_378_p2");
    sc_trace(mVcdFile, shl_ln166_1_fu_388_p3, "shl_ln166_1_fu_388_p3");
    sc_trace(mVcdFile, zext_ln166_9_fu_396_p1, "zext_ln166_9_fu_396_p1");
    sc_trace(mVcdFile, zext_ln163_fu_384_p1, "zext_ln163_fu_384_p1");
    sc_trace(mVcdFile, or_ln168_fu_406_p2, "or_ln168_fu_406_p2");
    sc_trace(mVcdFile, sext_ln168_fu_411_p1, "sext_ln168_fu_411_p1");
    sc_trace(mVcdFile, sext_ln166_1_fu_420_p1, "sext_ln166_1_fu_420_p1");
    sc_trace(mVcdFile, sext_ln167_fu_442_p1, "sext_ln167_fu_442_p1");
    sc_trace(mVcdFile, sext_ln168_1_fu_450_p1, "sext_ln168_1_fu_450_p1");
    sc_trace(mVcdFile, or_ln163_1_fu_458_p2, "or_ln163_1_fu_458_p2");
    sc_trace(mVcdFile, shl_ln166_2_fu_468_p3, "shl_ln166_2_fu_468_p3");
    sc_trace(mVcdFile, zext_ln166_10_fu_476_p1, "zext_ln166_10_fu_476_p1");
    sc_trace(mVcdFile, zext_ln163_1_fu_464_p1, "zext_ln163_1_fu_464_p1");
    sc_trace(mVcdFile, sext_ln166_2_fu_486_p1, "sext_ln166_2_fu_486_p1");
    sc_trace(mVcdFile, or_ln167_1_fu_494_p2, "or_ln167_1_fu_494_p2");
    sc_trace(mVcdFile, or_ln163_2_fu_514_p2, "or_ln163_2_fu_514_p2");
    sc_trace(mVcdFile, shl_ln166_3_fu_524_p3, "shl_ln166_3_fu_524_p3");
    sc_trace(mVcdFile, zext_ln166_11_fu_532_p1, "zext_ln166_11_fu_532_p1");
    sc_trace(mVcdFile, zext_ln163_2_fu_520_p1, "zext_ln163_2_fu_520_p1");
    sc_trace(mVcdFile, sext_ln168_2_fu_542_p1, "sext_ln168_2_fu_542_p1");
    sc_trace(mVcdFile, sext_ln166_3_fu_550_p1, "sext_ln166_3_fu_550_p1");
    sc_trace(mVcdFile, sext_ln167_1_fu_572_p1, "sext_ln167_1_fu_572_p1");
    sc_trace(mVcdFile, sext_ln168_3_fu_580_p1, "sext_ln168_3_fu_580_p1");
    sc_trace(mVcdFile, or_ln163_3_fu_588_p2, "or_ln163_3_fu_588_p2");
    sc_trace(mVcdFile, shl_ln166_4_fu_598_p3, "shl_ln166_4_fu_598_p3");
    sc_trace(mVcdFile, zext_ln166_12_fu_606_p1, "zext_ln166_12_fu_606_p1");
    sc_trace(mVcdFile, zext_ln163_3_fu_594_p1, "zext_ln163_3_fu_594_p1");
    sc_trace(mVcdFile, sext_ln166_4_fu_616_p1, "sext_ln166_4_fu_616_p1");
    sc_trace(mVcdFile, or_ln167_2_fu_624_p2, "or_ln167_2_fu_624_p2");
    sc_trace(mVcdFile, or_ln163_4_fu_639_p2, "or_ln163_4_fu_639_p2");
    sc_trace(mVcdFile, shl_ln166_5_fu_649_p3, "shl_ln166_5_fu_649_p3");
    sc_trace(mVcdFile, zext_ln166_13_fu_657_p1, "zext_ln166_13_fu_657_p1");
    sc_trace(mVcdFile, zext_ln163_4_fu_645_p1, "zext_ln163_4_fu_645_p1");
    sc_trace(mVcdFile, or_ln168_1_fu_667_p2, "or_ln168_1_fu_667_p2");
    sc_trace(mVcdFile, sext_ln168_4_fu_672_p1, "sext_ln168_4_fu_672_p1");
    sc_trace(mVcdFile, sext_ln166_5_fu_681_p1, "sext_ln166_5_fu_681_p1");
    sc_trace(mVcdFile, sext_ln167_2_fu_703_p1, "sext_ln167_2_fu_703_p1");
    sc_trace(mVcdFile, sext_ln168_5_fu_711_p1, "sext_ln168_5_fu_711_p1");
    sc_trace(mVcdFile, or_ln163_5_fu_719_p2, "or_ln163_5_fu_719_p2");
    sc_trace(mVcdFile, shl_ln166_6_fu_729_p3, "shl_ln166_6_fu_729_p3");
    sc_trace(mVcdFile, zext_ln166_14_fu_737_p1, "zext_ln166_14_fu_737_p1");
    sc_trace(mVcdFile, zext_ln163_5_fu_725_p1, "zext_ln163_5_fu_725_p1");
    sc_trace(mVcdFile, sext_ln166_6_fu_747_p1, "sext_ln166_6_fu_747_p1");
    sc_trace(mVcdFile, or_ln167_3_fu_755_p2, "or_ln167_3_fu_755_p2");
    sc_trace(mVcdFile, or_ln163_6_fu_775_p2, "or_ln163_6_fu_775_p2");
    sc_trace(mVcdFile, shl_ln166_7_fu_785_p3, "shl_ln166_7_fu_785_p3");
    sc_trace(mVcdFile, zext_ln166_15_fu_793_p1, "zext_ln166_15_fu_793_p1");
    sc_trace(mVcdFile, zext_ln163_6_fu_781_p1, "zext_ln163_6_fu_781_p1");
    sc_trace(mVcdFile, sext_ln168_6_fu_809_p1, "sext_ln168_6_fu_809_p1");
    sc_trace(mVcdFile, sext_ln166_7_fu_817_p1, "sext_ln166_7_fu_817_p1");
    sc_trace(mVcdFile, sext_ln167_3_fu_839_p1, "sext_ln167_3_fu_839_p1");
    sc_trace(mVcdFile, sext_ln168_7_fu_847_p1, "sext_ln168_7_fu_847_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

readFromBMP::~readFromBMP() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void readFromBMP::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        i_0_0_reg_283 = add_ln163_reg_985.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_0_reg_283 = ap_const_lv13_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1))) {
        add_ln163_reg_985 = add_ln163_fu_803_p2.read();
        add_ln168_4_reg_973 = add_ln168_4_fu_770_p2.read();
        sub_ln166_7_reg_978 = sub_ln166_7_fu_797_p2.read();
        trunc_ln168_6_reg_968 = trunc_ln168_6_fu_766_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1))) {
        add_ln167_1_reg_914 = add_ln167_1_fu_558_p2.read();
        add_ln168_2_reg_924 = add_ln168_2_fu_567_p2.read();
        trunc_ln168_3_reg_919 = trunc_ln168_3_fu_563_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1))) {
        add_ln167_2_reg_947 = add_ln167_2_fu_689_p2.read();
        add_ln168_3_reg_957 = add_ln168_3_fu_698_p2.read();
        trunc_ln168_5_reg_952 = trunc_ln168_5_fu_694_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1))) {
        add_ln167_3_reg_990 = add_ln167_3_fu_825_p2.read();
        add_ln168_5_reg_1000 = add_ln168_5_fu_834_p2.read();
        trunc_ln168_7_reg_995 = trunc_ln168_7_fu_830_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1))) {
        add_ln167_reg_876 = add_ln167_fu_428_p2.read();
        add_ln168_reg_886 = add_ln168_fu_437_p2.read();
        trunc_ln168_1_reg_881 = trunc_ln168_1_fu_433_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1))) {
        add_ln168_1_reg_902 = add_ln168_1_fu_509_p2.read();
        sub_ln166_3_reg_907 = sub_ln166_3_fu_536_p2.read();
        trunc_ln168_2_reg_897 = trunc_ln168_2_fu_505_p1.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
  esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
  esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
  esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
  esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)))) {
        reg_322 = rgb_in_TDATA.read().range(15, 8);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1))) {
        sub_ln166_1_reg_869 = sub_ln166_1_fu_400_p2.read();
        trunc_ln168_reg_864 = trunc_ln168_fu_374_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        sub_ln166_2_reg_891 = sub_ln166_2_fu_480_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        sub_ln166_4_reg_929 = sub_ln166_4_fu_610_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1))) {
        sub_ln166_5_reg_940 = sub_ln166_5_fu_661_p2.read();
        trunc_ln168_4_reg_935 = trunc_ln168_4_fu_635_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        sub_ln166_6_reg_962 = sub_ln166_6_fu_741_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln163_fu_331_p2.read(), ap_const_lv1_0))) {
        sub_ln166_reg_858 = sub_ln166_fu_349_p2.read();
    }
}

void readFromBMP::thread_JpegEncoder_buffer_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        JpegEncoder_buffer_address0 =  (sc_lv<14>) (zext_ln167_7_fu_842_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        JpegEncoder_buffer_address0 =  (sc_lv<14>) (zext_ln168_6_fu_812_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        JpegEncoder_buffer_address0 =  (sc_lv<14>) (zext_ln166_6_fu_750_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        JpegEncoder_buffer_address0 =  (sc_lv<14>) (zext_ln167_5_fu_706_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        JpegEncoder_buffer_address0 =  (sc_lv<14>) (zext_ln168_4_fu_676_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        JpegEncoder_buffer_address0 =  (sc_lv<14>) (zext_ln166_4_fu_619_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        JpegEncoder_buffer_address0 =  (sc_lv<14>) (zext_ln167_3_fu_575_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        JpegEncoder_buffer_address0 =  (sc_lv<14>) (zext_ln168_2_fu_545_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        JpegEncoder_buffer_address0 =  (sc_lv<14>) (zext_ln166_2_fu_489_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        JpegEncoder_buffer_address0 =  (sc_lv<14>) (zext_ln167_1_fu_445_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        JpegEncoder_buffer_address0 =  (sc_lv<14>) (zext_ln168_fu_415_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        JpegEncoder_buffer_address0 =  (sc_lv<14>) (zext_ln166_fu_358_p1.read());
    } else {
        JpegEncoder_buffer_address0 = "XXXXXXXXXXXXXX";
    }
}

void readFromBMP::thread_JpegEncoder_buffer_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        JpegEncoder_buffer_address1 =  (sc_lv<14>) (zext_ln168_7_fu_850_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        JpegEncoder_buffer_address1 =  (sc_lv<14>) (zext_ln166_7_fu_820_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        JpegEncoder_buffer_address1 =  (sc_lv<14>) (zext_ln167_6_fu_761_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        JpegEncoder_buffer_address1 =  (sc_lv<14>) (zext_ln168_5_fu_714_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        JpegEncoder_buffer_address1 =  (sc_lv<14>) (zext_ln166_5_fu_684_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        JpegEncoder_buffer_address1 =  (sc_lv<14>) (zext_ln167_4_fu_630_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        JpegEncoder_buffer_address1 =  (sc_lv<14>) (zext_ln168_3_fu_583_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        JpegEncoder_buffer_address1 =  (sc_lv<14>) (zext_ln166_3_fu_553_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        JpegEncoder_buffer_address1 =  (sc_lv<14>) (zext_ln167_2_fu_500_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        JpegEncoder_buffer_address1 =  (sc_lv<14>) (zext_ln168_1_fu_453_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        JpegEncoder_buffer_address1 =  (sc_lv<14>) (zext_ln166_1_fu_423_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        JpegEncoder_buffer_address1 =  (sc_lv<14>) (zext_ln167_fu_369_p1.read());
    } else {
        JpegEncoder_buffer_address1 = "XXXXXXXXXXXXXX";
    }
}

void readFromBMP::thread_JpegEncoder_buffer_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()))) {
        JpegEncoder_buffer_ce0 = ap_const_logic_1;
    } else {
        JpegEncoder_buffer_ce0 = ap_const_logic_0;
    }
}

void readFromBMP::thread_JpegEncoder_buffer_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()))) {
        JpegEncoder_buffer_ce1 = ap_const_logic_1;
    } else {
        JpegEncoder_buffer_ce1 = ap_const_logic_0;
    }
}

void readFromBMP::thread_JpegEncoder_buffer_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        JpegEncoder_buffer_d0 = trunc_ln168_6_reg_968.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        JpegEncoder_buffer_d0 = trunc_ln168_4_reg_935.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        JpegEncoder_buffer_d0 = trunc_ln168_2_reg_897.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()))) {
        JpegEncoder_buffer_d0 = reg_322.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        JpegEncoder_buffer_d0 = trunc_ln168_reg_864.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        JpegEncoder_buffer_d0 = rgb_in_TDATA.read().range(23, 16);
    } else {
        JpegEncoder_buffer_d0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void readFromBMP::thread_JpegEncoder_buffer_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        JpegEncoder_buffer_d1 = trunc_ln168_7_reg_995.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        JpegEncoder_buffer_d1 = trunc_ln168_5_reg_952.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        JpegEncoder_buffer_d1 = trunc_ln168_3_reg_919.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        JpegEncoder_buffer_d1 = trunc_ln168_1_reg_881.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        JpegEncoder_buffer_d1 = rgb_in_TDATA.read().range(23, 16);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        JpegEncoder_buffer_d1 = rgb_in_TDATA.read().range(15, 8);
    } else {
        JpegEncoder_buffer_d1 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void readFromBMP::thread_JpegEncoder_buffer_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()))) {
        JpegEncoder_buffer_we0 = ap_const_logic_1;
    } else {
        JpegEncoder_buffer_we0 = ap_const_logic_0;
    }
}

void readFromBMP::thread_JpegEncoder_buffer_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()))) {
        JpegEncoder_buffer_we1 = ap_const_logic_1;
    } else {
        JpegEncoder_buffer_we1 = ap_const_logic_0;
    }
}

void readFromBMP::thread_add_ln163_fu_803_p2() {
    add_ln163_fu_803_p2 = (!ap_const_lv13_8.is_01() || !i_0_0_reg_283.read().is_01())? sc_lv<13>(): (sc_biguint<13>(ap_const_lv13_8) + sc_biguint<13>(i_0_0_reg_283.read()));
}

void readFromBMP::thread_add_ln167_1_fu_558_p2() {
    add_ln167_1_fu_558_p2 = (!ap_const_lv16_1.is_01() || !sub_ln166_3_reg_907.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_1) + sc_bigint<16>(sub_ln166_3_reg_907.read()));
}

void readFromBMP::thread_add_ln167_2_fu_689_p2() {
    add_ln167_2_fu_689_p2 = (!ap_const_lv16_1.is_01() || !sub_ln166_5_reg_940.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_1) + sc_bigint<16>(sub_ln166_5_reg_940.read()));
}

void readFromBMP::thread_add_ln167_3_fu_825_p2() {
    add_ln167_3_fu_825_p2 = (!ap_const_lv16_1.is_01() || !sub_ln166_7_reg_978.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_1) + sc_bigint<16>(sub_ln166_7_reg_978.read()));
}

void readFromBMP::thread_add_ln167_fu_428_p2() {
    add_ln167_fu_428_p2 = (!ap_const_lv16_1.is_01() || !sub_ln166_1_reg_869.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_1) + sc_bigint<16>(sub_ln166_1_reg_869.read()));
}

void readFromBMP::thread_add_ln168_1_fu_509_p2() {
    add_ln168_1_fu_509_p2 = (!ap_const_lv16_2.is_01() || !sub_ln166_2_reg_891.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_2) + sc_bigint<16>(sub_ln166_2_reg_891.read()));
}

void readFromBMP::thread_add_ln168_2_fu_567_p2() {
    add_ln168_2_fu_567_p2 = (!ap_const_lv16_2.is_01() || !sub_ln166_3_reg_907.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_2) + sc_bigint<16>(sub_ln166_3_reg_907.read()));
}

void readFromBMP::thread_add_ln168_3_fu_698_p2() {
    add_ln168_3_fu_698_p2 = (!ap_const_lv16_2.is_01() || !sub_ln166_5_reg_940.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_2) + sc_bigint<16>(sub_ln166_5_reg_940.read()));
}

void readFromBMP::thread_add_ln168_4_fu_770_p2() {
    add_ln168_4_fu_770_p2 = (!ap_const_lv16_2.is_01() || !sub_ln166_6_reg_962.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_2) + sc_bigint<16>(sub_ln166_6_reg_962.read()));
}

void readFromBMP::thread_add_ln168_5_fu_834_p2() {
    add_ln168_5_fu_834_p2 = (!ap_const_lv16_2.is_01() || !sub_ln166_7_reg_978.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_2) + sc_bigint<16>(sub_ln166_7_reg_978.read()));
}

void readFromBMP::thread_add_ln168_fu_437_p2() {
    add_ln168_fu_437_p2 = (!ap_const_lv16_2.is_01() || !sub_ln166_1_reg_869.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_2) + sc_bigint<16>(sub_ln166_1_reg_869.read()));
}

void readFromBMP::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void readFromBMP::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void readFromBMP::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void readFromBMP::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void readFromBMP::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void readFromBMP::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void readFromBMP::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void readFromBMP::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void readFromBMP::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void readFromBMP::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void readFromBMP::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void readFromBMP::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void readFromBMP::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void readFromBMP::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void readFromBMP::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(icmp_ln163_fu_331_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void readFromBMP::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void readFromBMP::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln163_fu_331_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void readFromBMP::thread_i_0_0_cast8_fu_327_p1() {
    i_0_0_cast8_fu_327_p1 = esl_zext<16,13>(i_0_0_reg_283.read());
}

void readFromBMP::thread_icmp_ln163_fu_331_p2() {
    icmp_ln163_fu_331_p2 = (!i_0_0_reg_283.read().is_01() || !ap_const_lv13_1400.is_01())? sc_lv<1>(): sc_lv<1>(i_0_0_reg_283.read() == ap_const_lv13_1400);
}

void readFromBMP::thread_or_ln163_1_fu_458_p2() {
    or_ln163_1_fu_458_p2 = (i_0_0_reg_283.read() | ap_const_lv13_2);
}

void readFromBMP::thread_or_ln163_2_fu_514_p2() {
    or_ln163_2_fu_514_p2 = (i_0_0_reg_283.read() | ap_const_lv13_3);
}

void readFromBMP::thread_or_ln163_3_fu_588_p2() {
    or_ln163_3_fu_588_p2 = (i_0_0_reg_283.read() | ap_const_lv13_4);
}

void readFromBMP::thread_or_ln163_4_fu_639_p2() {
    or_ln163_4_fu_639_p2 = (i_0_0_reg_283.read() | ap_const_lv13_5);
}

void readFromBMP::thread_or_ln163_5_fu_719_p2() {
    or_ln163_5_fu_719_p2 = (i_0_0_reg_283.read() | ap_const_lv13_6);
}

void readFromBMP::thread_or_ln163_6_fu_775_p2() {
    or_ln163_6_fu_775_p2 = (i_0_0_reg_283.read() | ap_const_lv13_7);
}

void readFromBMP::thread_or_ln163_fu_378_p2() {
    or_ln163_fu_378_p2 = (i_0_0_reg_283.read() | ap_const_lv13_1);
}

void readFromBMP::thread_or_ln167_1_fu_494_p2() {
    or_ln167_1_fu_494_p2 = (sext_ln166_2_fu_486_p1.read() | ap_const_lv32_1);
}

void readFromBMP::thread_or_ln167_2_fu_624_p2() {
    or_ln167_2_fu_624_p2 = (sext_ln166_4_fu_616_p1.read() | ap_const_lv32_1);
}

void readFromBMP::thread_or_ln167_3_fu_755_p2() {
    or_ln167_3_fu_755_p2 = (sext_ln166_6_fu_747_p1.read() | ap_const_lv32_1);
}

void readFromBMP::thread_or_ln167_fu_363_p2() {
    or_ln167_fu_363_p2 = (sext_ln166_fu_355_p1.read() | ap_const_lv32_1);
}

void readFromBMP::thread_or_ln168_1_fu_667_p2() {
    or_ln168_1_fu_667_p2 = (sub_ln166_4_reg_929.read() | ap_const_lv16_2);
}

void readFromBMP::thread_or_ln168_fu_406_p2() {
    or_ln168_fu_406_p2 = (sub_ln166_reg_858.read() | ap_const_lv16_2);
}

void readFromBMP::thread_rgb_in_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        rgb_in_TDATA_blk_n = rgb_in_TVALID.read();
    } else {
        rgb_in_TDATA_blk_n = ap_const_logic_1;
    }
}

void readFromBMP::thread_rgb_in_TREADY() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
          esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1)))) {
        rgb_in_TREADY = ap_const_logic_1;
    } else {
        rgb_in_TREADY = ap_const_logic_0;
    }
}

void readFromBMP::thread_sext_ln166_1_fu_420_p1() {
    sext_ln166_1_fu_420_p1 = esl_sext<32,16>(sub_ln166_1_reg_869.read());
}

void readFromBMP::thread_sext_ln166_2_fu_486_p1() {
    sext_ln166_2_fu_486_p1 = esl_sext<32,16>(sub_ln166_2_reg_891.read());
}

void readFromBMP::thread_sext_ln166_3_fu_550_p1() {
    sext_ln166_3_fu_550_p1 = esl_sext<32,16>(sub_ln166_3_reg_907.read());
}

void readFromBMP::thread_sext_ln166_4_fu_616_p1() {
    sext_ln166_4_fu_616_p1 = esl_sext<32,16>(sub_ln166_4_reg_929.read());
}

void readFromBMP::thread_sext_ln166_5_fu_681_p1() {
    sext_ln166_5_fu_681_p1 = esl_sext<32,16>(sub_ln166_5_reg_940.read());
}

void readFromBMP::thread_sext_ln166_6_fu_747_p1() {
    sext_ln166_6_fu_747_p1 = esl_sext<32,16>(sub_ln166_6_reg_962.read());
}

void readFromBMP::thread_sext_ln166_7_fu_817_p1() {
    sext_ln166_7_fu_817_p1 = esl_sext<32,16>(sub_ln166_7_reg_978.read());
}

void readFromBMP::thread_sext_ln166_fu_355_p1() {
    sext_ln166_fu_355_p1 = esl_sext<32,16>(sub_ln166_reg_858.read());
}

void readFromBMP::thread_sext_ln167_1_fu_572_p1() {
    sext_ln167_1_fu_572_p1 = esl_sext<32,16>(add_ln167_1_reg_914.read());
}

void readFromBMP::thread_sext_ln167_2_fu_703_p1() {
    sext_ln167_2_fu_703_p1 = esl_sext<32,16>(add_ln167_2_reg_947.read());
}

void readFromBMP::thread_sext_ln167_3_fu_839_p1() {
    sext_ln167_3_fu_839_p1 = esl_sext<32,16>(add_ln167_3_reg_990.read());
}

void readFromBMP::thread_sext_ln167_fu_442_p1() {
    sext_ln167_fu_442_p1 = esl_sext<32,16>(add_ln167_reg_876.read());
}

void readFromBMP::thread_sext_ln168_1_fu_450_p1() {
    sext_ln168_1_fu_450_p1 = esl_sext<32,16>(add_ln168_reg_886.read());
}

void readFromBMP::thread_sext_ln168_2_fu_542_p1() {
    sext_ln168_2_fu_542_p1 = esl_sext<32,16>(add_ln168_1_reg_902.read());
}

void readFromBMP::thread_sext_ln168_3_fu_580_p1() {
    sext_ln168_3_fu_580_p1 = esl_sext<32,16>(add_ln168_2_reg_924.read());
}

void readFromBMP::thread_sext_ln168_4_fu_672_p1() {
    sext_ln168_4_fu_672_p1 = esl_sext<32,16>(or_ln168_1_fu_667_p2.read());
}

void readFromBMP::thread_sext_ln168_5_fu_711_p1() {
    sext_ln168_5_fu_711_p1 = esl_sext<32,16>(add_ln168_3_reg_957.read());
}

void readFromBMP::thread_sext_ln168_6_fu_809_p1() {
    sext_ln168_6_fu_809_p1 = esl_sext<32,16>(add_ln168_4_reg_973.read());
}

void readFromBMP::thread_sext_ln168_7_fu_847_p1() {
    sext_ln168_7_fu_847_p1 = esl_sext<32,16>(add_ln168_5_reg_1000.read());
}

void readFromBMP::thread_sext_ln168_fu_411_p1() {
    sext_ln168_fu_411_p1 = esl_sext<32,16>(or_ln168_fu_406_p2.read());
}

void readFromBMP::thread_shl_ln166_1_fu_388_p3() {
    shl_ln166_1_fu_388_p3 = esl_concat<13,2>(or_ln163_fu_378_p2.read(), ap_const_lv2_0);
}

void readFromBMP::thread_shl_ln166_2_fu_468_p3() {
    shl_ln166_2_fu_468_p3 = esl_concat<13,2>(or_ln163_1_fu_458_p2.read(), ap_const_lv2_0);
}

void readFromBMP::thread_shl_ln166_3_fu_524_p3() {
    shl_ln166_3_fu_524_p3 = esl_concat<13,2>(or_ln163_2_fu_514_p2.read(), ap_const_lv2_0);
}

void readFromBMP::thread_shl_ln166_4_fu_598_p3() {
    shl_ln166_4_fu_598_p3 = esl_concat<13,2>(or_ln163_3_fu_588_p2.read(), ap_const_lv2_0);
}

void readFromBMP::thread_shl_ln166_5_fu_649_p3() {
    shl_ln166_5_fu_649_p3 = esl_concat<13,2>(or_ln163_4_fu_639_p2.read(), ap_const_lv2_0);
}

void readFromBMP::thread_shl_ln166_6_fu_729_p3() {
    shl_ln166_6_fu_729_p3 = esl_concat<13,2>(or_ln163_5_fu_719_p2.read(), ap_const_lv2_0);
}

void readFromBMP::thread_shl_ln166_7_fu_785_p3() {
    shl_ln166_7_fu_785_p3 = esl_concat<13,2>(or_ln163_6_fu_775_p2.read(), ap_const_lv2_0);
}

void readFromBMP::thread_shl_ln_fu_337_p3() {
    shl_ln_fu_337_p3 = esl_concat<13,2>(i_0_0_reg_283.read(), ap_const_lv2_0);
}

void readFromBMP::thread_sub_ln166_1_fu_400_p2() {
    sub_ln166_1_fu_400_p2 = (!zext_ln166_9_fu_396_p1.read().is_01() || !zext_ln163_fu_384_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(zext_ln166_9_fu_396_p1.read()) - sc_biguint<16>(zext_ln163_fu_384_p1.read()));
}

void readFromBMP::thread_sub_ln166_2_fu_480_p2() {
    sub_ln166_2_fu_480_p2 = (!zext_ln166_10_fu_476_p1.read().is_01() || !zext_ln163_1_fu_464_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(zext_ln166_10_fu_476_p1.read()) - sc_biguint<16>(zext_ln163_1_fu_464_p1.read()));
}

void readFromBMP::thread_sub_ln166_3_fu_536_p2() {
    sub_ln166_3_fu_536_p2 = (!zext_ln166_11_fu_532_p1.read().is_01() || !zext_ln163_2_fu_520_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(zext_ln166_11_fu_532_p1.read()) - sc_biguint<16>(zext_ln163_2_fu_520_p1.read()));
}

void readFromBMP::thread_sub_ln166_4_fu_610_p2() {
    sub_ln166_4_fu_610_p2 = (!zext_ln166_12_fu_606_p1.read().is_01() || !zext_ln163_3_fu_594_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(zext_ln166_12_fu_606_p1.read()) - sc_biguint<16>(zext_ln163_3_fu_594_p1.read()));
}

void readFromBMP::thread_sub_ln166_5_fu_661_p2() {
    sub_ln166_5_fu_661_p2 = (!zext_ln166_13_fu_657_p1.read().is_01() || !zext_ln163_4_fu_645_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(zext_ln166_13_fu_657_p1.read()) - sc_biguint<16>(zext_ln163_4_fu_645_p1.read()));
}

void readFromBMP::thread_sub_ln166_6_fu_741_p2() {
    sub_ln166_6_fu_741_p2 = (!zext_ln166_14_fu_737_p1.read().is_01() || !zext_ln163_5_fu_725_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(zext_ln166_14_fu_737_p1.read()) - sc_biguint<16>(zext_ln163_5_fu_725_p1.read()));
}

void readFromBMP::thread_sub_ln166_7_fu_797_p2() {
    sub_ln166_7_fu_797_p2 = (!zext_ln166_15_fu_793_p1.read().is_01() || !zext_ln163_6_fu_781_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(zext_ln166_15_fu_793_p1.read()) - sc_biguint<16>(zext_ln163_6_fu_781_p1.read()));
}

void readFromBMP::thread_sub_ln166_fu_349_p2() {
    sub_ln166_fu_349_p2 = (!zext_ln166_8_fu_345_p1.read().is_01() || !i_0_0_cast8_fu_327_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(zext_ln166_8_fu_345_p1.read()) - sc_biguint<16>(i_0_0_cast8_fu_327_p1.read()));
}

void readFromBMP::thread_trunc_ln168_1_fu_433_p1() {
    trunc_ln168_1_fu_433_p1 = rgb_in_TDATA.read().range(8-1, 0);
}

void readFromBMP::thread_trunc_ln168_2_fu_505_p1() {
    trunc_ln168_2_fu_505_p1 = rgb_in_TDATA.read().range(8-1, 0);
}

void readFromBMP::thread_trunc_ln168_3_fu_563_p1() {
    trunc_ln168_3_fu_563_p1 = rgb_in_TDATA.read().range(8-1, 0);
}

void readFromBMP::thread_trunc_ln168_4_fu_635_p1() {
    trunc_ln168_4_fu_635_p1 = rgb_in_TDATA.read().range(8-1, 0);
}

void readFromBMP::thread_trunc_ln168_5_fu_694_p1() {
    trunc_ln168_5_fu_694_p1 = rgb_in_TDATA.read().range(8-1, 0);
}

void readFromBMP::thread_trunc_ln168_6_fu_766_p1() {
    trunc_ln168_6_fu_766_p1 = rgb_in_TDATA.read().range(8-1, 0);
}

void readFromBMP::thread_trunc_ln168_7_fu_830_p1() {
    trunc_ln168_7_fu_830_p1 = rgb_in_TDATA.read().range(8-1, 0);
}

void readFromBMP::thread_trunc_ln168_fu_374_p1() {
    trunc_ln168_fu_374_p1 = rgb_in_TDATA.read().range(8-1, 0);
}

void readFromBMP::thread_zext_ln163_1_fu_464_p1() {
    zext_ln163_1_fu_464_p1 = esl_zext<16,13>(or_ln163_1_fu_458_p2.read());
}

void readFromBMP::thread_zext_ln163_2_fu_520_p1() {
    zext_ln163_2_fu_520_p1 = esl_zext<16,13>(or_ln163_2_fu_514_p2.read());
}

void readFromBMP::thread_zext_ln163_3_fu_594_p1() {
    zext_ln163_3_fu_594_p1 = esl_zext<16,13>(or_ln163_3_fu_588_p2.read());
}

void readFromBMP::thread_zext_ln163_4_fu_645_p1() {
    zext_ln163_4_fu_645_p1 = esl_zext<16,13>(or_ln163_4_fu_639_p2.read());
}

void readFromBMP::thread_zext_ln163_5_fu_725_p1() {
    zext_ln163_5_fu_725_p1 = esl_zext<16,13>(or_ln163_5_fu_719_p2.read());
}

void readFromBMP::thread_zext_ln163_6_fu_781_p1() {
    zext_ln163_6_fu_781_p1 = esl_zext<16,13>(or_ln163_6_fu_775_p2.read());
}

void readFromBMP::thread_zext_ln163_fu_384_p1() {
    zext_ln163_fu_384_p1 = esl_zext<16,13>(or_ln163_fu_378_p2.read());
}

void readFromBMP::thread_zext_ln166_10_fu_476_p1() {
    zext_ln166_10_fu_476_p1 = esl_zext<16,15>(shl_ln166_2_fu_468_p3.read());
}

void readFromBMP::thread_zext_ln166_11_fu_532_p1() {
    zext_ln166_11_fu_532_p1 = esl_zext<16,15>(shl_ln166_3_fu_524_p3.read());
}

void readFromBMP::thread_zext_ln166_12_fu_606_p1() {
    zext_ln166_12_fu_606_p1 = esl_zext<16,15>(shl_ln166_4_fu_598_p3.read());
}

void readFromBMP::thread_zext_ln166_13_fu_657_p1() {
    zext_ln166_13_fu_657_p1 = esl_zext<16,15>(shl_ln166_5_fu_649_p3.read());
}

void readFromBMP::thread_zext_ln166_14_fu_737_p1() {
    zext_ln166_14_fu_737_p1 = esl_zext<16,15>(shl_ln166_6_fu_729_p3.read());
}

void readFromBMP::thread_zext_ln166_15_fu_793_p1() {
    zext_ln166_15_fu_793_p1 = esl_zext<16,15>(shl_ln166_7_fu_785_p3.read());
}

void readFromBMP::thread_zext_ln166_1_fu_423_p1() {
    zext_ln166_1_fu_423_p1 = esl_zext<64,32>(sext_ln166_1_fu_420_p1.read());
}

void readFromBMP::thread_zext_ln166_2_fu_489_p1() {
    zext_ln166_2_fu_489_p1 = esl_zext<64,32>(sext_ln166_2_fu_486_p1.read());
}

void readFromBMP::thread_zext_ln166_3_fu_553_p1() {
    zext_ln166_3_fu_553_p1 = esl_zext<64,32>(sext_ln166_3_fu_550_p1.read());
}

void readFromBMP::thread_zext_ln166_4_fu_619_p1() {
    zext_ln166_4_fu_619_p1 = esl_zext<64,32>(sext_ln166_4_fu_616_p1.read());
}

void readFromBMP::thread_zext_ln166_5_fu_684_p1() {
    zext_ln166_5_fu_684_p1 = esl_zext<64,32>(sext_ln166_5_fu_681_p1.read());
}

void readFromBMP::thread_zext_ln166_6_fu_750_p1() {
    zext_ln166_6_fu_750_p1 = esl_zext<64,32>(sext_ln166_6_fu_747_p1.read());
}

void readFromBMP::thread_zext_ln166_7_fu_820_p1() {
    zext_ln166_7_fu_820_p1 = esl_zext<64,32>(sext_ln166_7_fu_817_p1.read());
}

void readFromBMP::thread_zext_ln166_8_fu_345_p1() {
    zext_ln166_8_fu_345_p1 = esl_zext<16,15>(shl_ln_fu_337_p3.read());
}

void readFromBMP::thread_zext_ln166_9_fu_396_p1() {
    zext_ln166_9_fu_396_p1 = esl_zext<16,15>(shl_ln166_1_fu_388_p3.read());
}

void readFromBMP::thread_zext_ln166_fu_358_p1() {
    zext_ln166_fu_358_p1 = esl_zext<64,32>(sext_ln166_fu_355_p1.read());
}

void readFromBMP::thread_zext_ln167_1_fu_445_p1() {
    zext_ln167_1_fu_445_p1 = esl_zext<64,32>(sext_ln167_fu_442_p1.read());
}

void readFromBMP::thread_zext_ln167_2_fu_500_p1() {
    zext_ln167_2_fu_500_p1 = esl_zext<64,32>(or_ln167_1_fu_494_p2.read());
}

void readFromBMP::thread_zext_ln167_3_fu_575_p1() {
    zext_ln167_3_fu_575_p1 = esl_zext<64,32>(sext_ln167_1_fu_572_p1.read());
}

void readFromBMP::thread_zext_ln167_4_fu_630_p1() {
    zext_ln167_4_fu_630_p1 = esl_zext<64,32>(or_ln167_2_fu_624_p2.read());
}

void readFromBMP::thread_zext_ln167_5_fu_706_p1() {
    zext_ln167_5_fu_706_p1 = esl_zext<64,32>(sext_ln167_2_fu_703_p1.read());
}

void readFromBMP::thread_zext_ln167_6_fu_761_p1() {
    zext_ln167_6_fu_761_p1 = esl_zext<64,32>(or_ln167_3_fu_755_p2.read());
}

void readFromBMP::thread_zext_ln167_7_fu_842_p1() {
    zext_ln167_7_fu_842_p1 = esl_zext<64,32>(sext_ln167_3_fu_839_p1.read());
}

void readFromBMP::thread_zext_ln167_fu_369_p1() {
    zext_ln167_fu_369_p1 = esl_zext<64,32>(or_ln167_fu_363_p2.read());
}

void readFromBMP::thread_zext_ln168_1_fu_453_p1() {
    zext_ln168_1_fu_453_p1 = esl_zext<64,32>(sext_ln168_1_fu_450_p1.read());
}

void readFromBMP::thread_zext_ln168_2_fu_545_p1() {
    zext_ln168_2_fu_545_p1 = esl_zext<64,32>(sext_ln168_2_fu_542_p1.read());
}

void readFromBMP::thread_zext_ln168_3_fu_583_p1() {
    zext_ln168_3_fu_583_p1 = esl_zext<64,32>(sext_ln168_3_fu_580_p1.read());
}

void readFromBMP::thread_zext_ln168_4_fu_676_p1() {
    zext_ln168_4_fu_676_p1 = esl_zext<64,32>(sext_ln168_4_fu_672_p1.read());
}

void readFromBMP::thread_zext_ln168_5_fu_714_p1() {
    zext_ln168_5_fu_714_p1 = esl_zext<64,32>(sext_ln168_5_fu_711_p1.read());
}

void readFromBMP::thread_zext_ln168_6_fu_812_p1() {
    zext_ln168_6_fu_812_p1 = esl_zext<64,32>(sext_ln168_6_fu_809_p1.read());
}

void readFromBMP::thread_zext_ln168_7_fu_850_p1() {
    zext_ln168_7_fu_850_p1 = esl_zext<64,32>(sext_ln168_7_fu_847_p1.read());
}

void readFromBMP::thread_zext_ln168_fu_415_p1() {
    zext_ln168_fu_415_p1 = esl_zext<64,32>(sext_ln168_fu_411_p1.read());
}

void readFromBMP::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln163_fu_331_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 512 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_state12;
            }
            break;
        case 4096 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && esl_seteq<1,1,1>(rgb_in_TVALID.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state14;
            } else {
                ap_NS_fsm = ap_ST_fsm_state13;
            }
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXXXXXX";
            break;
    }
}

}

